# Generated by Django 5.0.2 on 2026-07-29 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_phase_and_org_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentPlantScope",
            fields=[
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="plant_scopes",
                        serialize=False,
                        to="plants.department",
                    ),
                ),
            ],
            options={
                "db_table": "department_plant_scope",
                "managed": False,
            },
        ),
    ]
