# Generated by Django 5.0.2 on 2026-08-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('plants', '0003_departmentplantscope'),
]    
    operations = []
