# Generated by Django 5.0.2 on 2026-08-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0005_restructure_org_hierarchy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orgpositiondepartmentscope",
            options={"managed": False},
        ),
    ]
