# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("factory", "0025_conformityrule_max_value_conformityrule_min_value_and_more"),
        ("plants", "0007_rename_plant_code_to_product_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=30, unique=True)),
                ("product_name", models.CharField(max_length=150)),
                ("product_type", models.CharField(blank=True, max_length=50)),
                ("unit_of_measure", models.CharField(default="tons", max_length=20)),
                ("traceability_level", models.PositiveSmallIntegerField(default=1)),
                ("batch_required", models.BooleanField(default=True)),
                ("chemical_tests_required", models.BooleanField(default=True)),
                ("physical_tests_required", models.BooleanField(default=True)),
                ("stock_product", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "packing_types",
                    models.ManyToManyField(blank=True, to="factory.packingtype"),
                ),
                (
                    "plants",
                    models.ManyToManyField(
                        blank=True, related_name="finished_products", to="plants.plant"
                    ),
                ),
            ],
            options={
                "db_table": "finished_products_products",
                "ordering": ["product_name"],
            },
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("production_in", "Production In"),
                            ("reserved", "Reserved"),
                            ("released", "Released"),
                            ("issued", "Issued"),
                            ("adjustment_in", "Adjustment In"),
                            ("adjustment_out", "Adjustment Out"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reference_text", models.CharField(blank=True, max_length=200)),
                ("occurred_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "packaging_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="factory.packingtype",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finished_stock_ledger",
                        to="plants.plant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="finished_products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finished_products_stock_ledger",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "reserved",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "available",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "under_preparation",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "qc_hold",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "packaging_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="factory.packingtype",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finished_stock_balances",
                        to="plants.plant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="finished_products.product",
                    ),
                ),
            ],
            options={
                "db_table": "finished_products_stock_balances",
                "unique_together": {("plant", "product", "packaging_type")},
            },
        ),
    ]
