--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

-- Started on 2026-07-22 18:41:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 278 (class 1255 OID 16986)
-- Name: get_group_shift(character varying, date); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.get_group_shift(p_group_name character varying, p_date date) RETURNS character varying
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_offset INT;
    v_shift_name VARCHAR;
    v_ref_date DATE;
BEGIN
    SELECT reference_date INTO v_ref_date FROM rotation_reference LIMIT 1;

    v_offset := MOD((p_date - v_ref_date)::INT, 8);
    IF v_offset < 0 THEN
        v_offset := v_offset + 8;
    END IF;

    SELECT st.shift_type_name INTO v_shift_name
    FROM shift_rotation_pattern srp
    JOIN shift_groups sg ON sg.group_id = srp.group_id
    JOIN shift_types st ON st.shift_type_id = srp.shift_type_id
    WHERE sg.group_name = p_group_name AND srp.day_offset = v_offset;

    RETURN v_shift_name;
END;
$$;


ALTER FUNCTION public.get_group_shift(p_group_name character varying, p_date date) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 257 (class 1259 OID 17141)
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_userprofile (
    id bigint NOT NULL,
    org_position_id integer,
    user_id integer NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 17140)
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 17016)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17015)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17024)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 17023)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 17010)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17009)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 17030)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 17038)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17037)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 17029)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 17044)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 17043)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16863)
-- Name: department_plant_scope; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department_plant_scope (
    department_id integer NOT NULL,
    plant_id integer NOT NULL
);


ALTER TABLE public.department_plant_scope OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16844)
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    department_id integer NOT NULL,
    department_code character varying(20) NOT NULL,
    department_name character varying(50) NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16843)
-- Name: departments_department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.departments_department_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.departments_department_id_seq OWNER TO postgres;

--
-- TOC entry 5208 (class 0 OID 0)
-- Dependencies: 219
-- Name: departments_department_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.departments_department_id_seq OWNED BY public.departments.department_id;


--
-- TOC entry 254 (class 1259 OID 17102)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 17101)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17002)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17001)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16994)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16993)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 17130)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16952)
-- Name: employee_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_assignments (
    assignment_id integer NOT NULL,
    employee_id integer NOT NULL,
    position_id integer NOT NULL,
    shift_mode character varying(10) NOT NULL,
    group_id integer,
    fixed_shift_type_id integer,
    start_date date DEFAULT CURRENT_DATE NOT NULL,
    end_date date,
    is_current boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_shift_mode_link CHECK (((((shift_mode)::text = 'rotating'::text) AND (group_id IS NOT NULL) AND (fixed_shift_type_id IS NULL)) OR (((shift_mode)::text = 'fixed'::text) AND (fixed_shift_type_id IS NOT NULL) AND (group_id IS NULL)))),
    CONSTRAINT employee_assignments_shift_mode_check CHECK (((shift_mode)::text = ANY ((ARRAY['rotating'::character varying, 'fixed'::character varying])::text[])))
);


ALTER TABLE public.employee_assignments OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16951)
-- Name: employee_assignments_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.employee_assignments_assignment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employee_assignments_assignment_id_seq OWNER TO postgres;

--
-- TOC entry 5209 (class 0 OID 0)
-- Dependencies: 234
-- Name: employee_assignments_assignment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.employee_assignments_assignment_id_seq OWNED BY public.employee_assignments.assignment_id;


--
-- TOC entry 233 (class 1259 OID 16942)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    employee_id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    national_id character varying(20),
    phone character varying(20),
    hire_date date,
    is_active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16941)
-- Name: employees_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.employees_employee_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employees_employee_id_seq OWNER TO postgres;

--
-- TOC entry 5210 (class 0 OID 0)
-- Dependencies: 232
-- Name: employees_employee_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.employees_employee_id_seq OWNED BY public.employees.employee_id;


--
-- TOC entry 225 (class 1259 OID 16879)
-- Name: org_positions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.org_positions (
    position_id integer NOT NULL,
    entity_type character varying(10) NOT NULL,
    plant_id integer,
    department_id integer,
    role_id integer NOT NULL,
    hierarchy_level integer NOT NULL,
    CONSTRAINT chk_entity_link CHECK (((((entity_type)::text = 'plant'::text) AND (plant_id IS NOT NULL) AND (department_id IS NULL)) OR (((entity_type)::text = 'department'::text) AND (department_id IS NOT NULL) AND (plant_id IS NULL)))),
    CONSTRAINT org_positions_entity_type_check CHECK (((entity_type)::text = ANY ((ARRAY['plant'::character varying, 'department'::character varying])::text[])))
);


ALTER TABLE public.org_positions OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16878)
-- Name: org_positions_position_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.org_positions_position_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.org_positions_position_id_seq OWNER TO postgres;

--
-- TOC entry 5211 (class 0 OID 0)
-- Dependencies: 224
-- Name: org_positions_position_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.org_positions_position_id_seq OWNED BY public.org_positions.position_id;


--
-- TOC entry 218 (class 1259 OID 16833)
-- Name: plants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plants (
    plant_id integer NOT NULL,
    plant_code character varying(20) NOT NULL,
    plant_name character varying(50) NOT NULL,
    phase smallint
);


ALTER TABLE public.plants OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16832)
-- Name: plants_plant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.plants_plant_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.plants_plant_id_seq OWNER TO postgres;

--
-- TOC entry 5212 (class 0 OID 0)
-- Dependencies: 217
-- Name: plants_plant_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.plants_plant_id_seq OWNED BY public.plants.plant_id;


--
-- TOC entry 265 (class 1259 OID 17183)
-- Name: production_bigbag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_bigbag (
    id bigint NOT NULL,
    bag_number integer NOT NULL,
    status character varying(20) NOT NULL,
    packed_at timestamp with time zone NOT NULL,
    production_batch_id bigint NOT NULL,
    CONSTRAINT production_bigbag_bag_number_check CHECK ((bag_number >= 0))
);


ALTER TABLE public.production_bigbag OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 17182)
-- Name: production_bigbag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_bigbag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_bigbag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 17160)
-- Name: production_customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_customer (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    is_export boolean NOT NULL
);


ALTER TABLE public.production_customer OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 17159)
-- Name: production_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 17213)
-- Name: production_orderbatch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_orderbatch (
    id bigint NOT NULL,
    order_reference character varying(50) NOT NULL,
    total_weight_kg numeric(12,2) NOT NULL,
    dispatched_at timestamp with time zone,
    customer_id bigint NOT NULL
);


ALTER TABLE public.production_orderbatch OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 17212)
-- Name: production_orderbatch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_orderbatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_orderbatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 17227)
-- Name: production_orderbatch_sack_conversions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_orderbatch_sack_conversions (
    id bigint NOT NULL,
    orderbatch_id bigint NOT NULL,
    sackconversion_id bigint NOT NULL
);


ALTER TABLE public.production_orderbatch_sack_conversions OWNER TO postgres;

--
-- TOC entry 274 (class 1259 OID 17226)
-- Name: production_orderbatch_sack_conversions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_orderbatch_sack_conversions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_orderbatch_sack_conversions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 17221)
-- Name: production_orderbatch_whole_big_bags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_orderbatch_whole_big_bags (
    id bigint NOT NULL,
    orderbatch_id bigint NOT NULL,
    bigbag_id bigint NOT NULL
);


ALTER TABLE public.production_orderbatch_whole_big_bags OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 17220)
-- Name: production_orderbatch_whole_big_bags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_orderbatch_whole_big_bags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_orderbatch_whole_big_bags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 17166)
-- Name: production_productionbatch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_productionbatch (
    id bigint NOT NULL,
    sequence_number integer NOT NULL,
    produced_at timestamp with time zone NOT NULL,
    production_run_id bigint NOT NULL,
    silo_id bigint NOT NULL,
    CONSTRAINT production_productionbatch_sequence_number_check CHECK ((sequence_number >= 0))
);


ALTER TABLE public.production_productionbatch OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 17165)
-- Name: production_productionbatch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_productionbatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_productionbatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 17192)
-- Name: production_productionrun; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_productionrun (
    id bigint NOT NULL,
    run_number integer NOT NULL,
    started_at date NOT NULL,
    ended_at date,
    is_closed boolean NOT NULL,
    plant_id integer NOT NULL,
    CONSTRAINT production_productionrun_run_number_check CHECK ((run_number >= 0))
);


ALTER TABLE public.production_productionrun OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 17191)
-- Name: production_productionrun_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_productionrun ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_productionrun_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 17204)
-- Name: production_sackconversion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_sackconversion (
    id bigint NOT NULL,
    sack_count integer NOT NULL,
    converted_at timestamp with time zone NOT NULL,
    big_bag_id bigint NOT NULL,
    sack_type_id bigint NOT NULL,
    CONSTRAINT production_sackconversion_sack_count_check CHECK ((sack_count >= 0))
);


ALTER TABLE public.production_sackconversion OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 17203)
-- Name: production_sackconversion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_sackconversion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_sackconversion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 17175)
-- Name: production_sacktype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_sacktype (
    id bigint NOT NULL,
    name character varying(30) NOT NULL,
    nominal_weight_kg numeric(6,2) NOT NULL
);


ALTER TABLE public.production_sacktype OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 17174)
-- Name: production_sacktype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_sacktype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_sacktype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 277 (class 1259 OID 17233)
-- Name: production_silo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.production_silo (
    id bigint NOT NULL,
    code character varying(10) NOT NULL,
    plant_id integer NOT NULL
);


ALTER TABLE public.production_silo OWNER TO postgres;

--
-- TOC entry 276 (class 1259 OID 17232)
-- Name: production_silo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.production_silo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_silo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16855)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_name character varying(50) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16854)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.roles_role_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.roles_role_id_seq OWNER TO postgres;

--
-- TOC entry 5213 (class 0 OID 0)
-- Dependencies: 221
-- Name: roles_role_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.roles_role_id_seq OWNED BY public.roles.role_id;


--
-- TOC entry 231 (class 1259 OID 16938)
-- Name: rotation_reference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rotation_reference (
    reference_date date NOT NULL
);


ALTER TABLE public.rotation_reference OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16914)
-- Name: shift_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shift_groups (
    group_id integer NOT NULL,
    group_name character varying(5) NOT NULL
);


ALTER TABLE public.shift_groups OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16913)
-- Name: shift_groups_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.shift_groups_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.shift_groups_group_id_seq OWNER TO postgres;

--
-- TOC entry 5214 (class 0 OID 0)
-- Dependencies: 228
-- Name: shift_groups_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.shift_groups_group_id_seq OWNED BY public.shift_groups.group_id;


--
-- TOC entry 230 (class 1259 OID 16922)
-- Name: shift_rotation_pattern; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shift_rotation_pattern (
    group_id integer NOT NULL,
    day_offset integer NOT NULL,
    shift_type_id integer NOT NULL,
    CONSTRAINT shift_rotation_pattern_day_offset_check CHECK (((day_offset >= 0) AND (day_offset <= 7)))
);


ALTER TABLE public.shift_rotation_pattern OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16905)
-- Name: shift_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shift_types (
    shift_type_id integer NOT NULL,
    shift_type_name character varying(20) NOT NULL,
    start_time time without time zone,
    end_time time without time zone
);


ALTER TABLE public.shift_types OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16904)
-- Name: shift_types_shift_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.shift_types_shift_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.shift_types_shift_type_id_seq OWNER TO postgres;

--
-- TOC entry 5215 (class 0 OID 0)
-- Dependencies: 226
-- Name: shift_types_shift_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.shift_types_shift_type_id_seq OWNED BY public.shift_types.shift_type_id;


--
-- TOC entry 236 (class 1259 OID 16987)
-- Name: v_today_shift_rotating; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.v_today_shift_rotating AS
 SELECT e.employee_id,
    e.full_name,
    sg.group_name,
    public.get_group_shift(sg.group_name, CURRENT_DATE) AS today_shift
   FROM ((public.employee_assignments ea
     JOIN public.employees e ON ((e.employee_id = ea.employee_id)))
     JOIN public.shift_groups sg ON ((sg.group_id = ea.group_id)))
  WHERE (((ea.shift_mode)::text = 'rotating'::text) AND (ea.is_current = true));


ALTER VIEW public.v_today_shift_rotating OWNER TO postgres;

--
-- TOC entry 4798 (class 2604 OID 16847)
-- Name: departments department_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments ALTER COLUMN department_id SET DEFAULT nextval('public.departments_department_id_seq'::regclass);


--
-- TOC entry 4805 (class 2604 OID 16955)
-- Name: employee_assignments assignment_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_assignments ALTER COLUMN assignment_id SET DEFAULT nextval('public.employee_assignments_assignment_id_seq'::regclass);


--
-- TOC entry 4803 (class 2604 OID 16945)
-- Name: employees employee_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees ALTER COLUMN employee_id SET DEFAULT nextval('public.employees_employee_id_seq'::regclass);


--
-- TOC entry 4800 (class 2604 OID 16882)
-- Name: org_positions position_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.org_positions ALTER COLUMN position_id SET DEFAULT nextval('public.org_positions_position_id_seq'::regclass);


--
-- TOC entry 4797 (class 2604 OID 16836)
-- Name: plants plant_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plants ALTER COLUMN plant_id SET DEFAULT nextval('public.plants_plant_id_seq'::regclass);


--
-- TOC entry 4799 (class 2604 OID 16858)
-- Name: roles role_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles ALTER COLUMN role_id SET DEFAULT nextval('public.roles_role_id_seq'::regclass);


--
-- TOC entry 4802 (class 2604 OID 16917)
-- Name: shift_groups group_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_groups ALTER COLUMN group_id SET DEFAULT nextval('public.shift_groups_group_id_seq'::regclass);


--
-- TOC entry 4801 (class 2604 OID 16908)
-- Name: shift_types shift_type_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_types ALTER COLUMN shift_type_id SET DEFAULT nextval('public.shift_types_shift_type_id_seq'::regclass);


--
-- TOC entry 5182 (class 0 OID 17141)
-- Dependencies: 257
-- Data for Name: accounts_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_userprofile (id, org_position_id, user_id) FROM stdin;
\.


--
-- TOC entry 5169 (class 0 OID 17016)
-- Dependencies: 244
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5171 (class 0 OID 17024)
-- Dependencies: 246
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5167 (class 0 OID 17010)
-- Dependencies: 242
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add plant	9	add_plant
26	Can change plant	9	change_plant
27	Can delete plant	9	delete_plant
28	Can view plant	9	view_plant
29	Can add department	7	add_department
30	Can change department	7	change_department
31	Can delete department	7	delete_department
32	Can view department	7	view_department
33	Can add role	10	add_role
34	Can change role	10	change_role
35	Can delete role	10	delete_role
36	Can view role	10	view_role
37	Can add org position	8	add_orgposition
38	Can change org position	8	change_orgposition
39	Can delete org position	8	delete_orgposition
40	Can view org position	8	view_orgposition
41	Can add User Profile (ملف المستخدم)	11	add_userprofile
42	Can change User Profile (ملف المستخدم)	11	change_userprofile
43	Can delete User Profile (ملف المستخدم)	11	delete_userprofile
44	Can view User Profile (ملف المستخدم)	11	view_userprofile
45	Can add Sack Type (نوع الشكارة)	18	add_sacktype
46	Can change Sack Type (نوع الشكارة)	18	change_sacktype
47	Can delete Sack Type (نوع الشكارة)	18	delete_sacktype
48	Can view Sack Type (نوع الشكارة)	18	view_sacktype
49	Can add Order Batch (باتش الطلبية)	14	add_orderbatch
50	Can change Order Batch (باتش الطلبية)	14	change_orderbatch
51	Can delete Order Batch (باتش الطلبية)	14	delete_orderbatch
52	Can view Order Batch (باتش الطلبية)	14	view_orderbatch
53	Can add Production Run (تشغيلة)	16	add_productionrun
54	Can change Production Run (تشغيلة)	16	change_productionrun
55	Can delete Production Run (تشغيلة)	16	delete_productionrun
56	Can view Production Run (تشغيلة)	16	view_productionrun
57	Can add Silo (سيلو)	19	add_silo
58	Can change Silo (سيلو)	19	change_silo
59	Can delete Silo (سيلو)	19	delete_silo
60	Can view Silo (سيلو)	19	view_silo
61	Can add Customer (عميل)	13	add_customer
62	Can change Customer (عميل)	13	change_customer
63	Can delete Customer (عميل)	13	delete_customer
64	Can view Customer (عميل)	13	view_customer
65	Can add Sack Conversion (تحويل لشكاير)	17	add_sackconversion
66	Can change Sack Conversion (تحويل لشكاير)	17	change_sackconversion
67	Can delete Sack Conversion (تحويل لشكاير)	17	delete_sackconversion
68	Can view Sack Conversion (تحويل لشكاير)	17	view_sackconversion
69	Can add Production Batch (كود الجودة)	15	add_productionbatch
70	Can change Production Batch (كود الجودة)	15	change_productionbatch
71	Can delete Production Batch (كود الجودة)	15	delete_productionbatch
72	Can view Production Batch (كود الجودة)	15	view_productionbatch
73	Can add Big Bag (بيج باج)	12	add_bigbag
74	Can change Big Bag (بيج باج)	12	change_bigbag
75	Can delete Big Bag (بيج باج)	12	delete_bigbag
76	Can view Big Bag (بيج باج)	12	view_bigbag
\.


--
-- TOC entry 5173 (class 0 OID 17030)
-- Dependencies: 248
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1200000$H5O5tKowsXeEC19sDQAhaA$u6F+2SxuqyS0AQKyziprfuQ0vV2/aCYXpVo8yicJty4=	2026-07-21 12:19:33.208982+03	t	admin				t	t	2026-07-21 12:05:04.254472+03
1	pbkdf2_sha256$1200000$QO6aoXoXRelfQISa8hmM4p$ApfliYzC9MFjXTtgpXVRBqsa/FdgPhIneFsNIwdAHuM=	2026-07-21 22:31:50.67356+03	t	Eng_Abdullah				t	t	2026-07-21 11:58:21.314696+03
\.


--
-- TOC entry 5175 (class 0 OID 17038)
-- Dependencies: 250
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5177 (class 0 OID 17044)
-- Dependencies: 252
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5149 (class 0 OID 16863)
-- Dependencies: 223
-- Data for Name: department_plant_scope; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.department_plant_scope (department_id, plant_id) FROM stdin;
1	1
1	12
1	2
1	3
1	4
1	5
1	6
1	7
1	8
1	9
1	10
1	11
2	1
2	12
2	2
2	3
2	4
2	5
2	6
2	7
2	8
2	9
2	10
2	11
3	12
3	5
3	6
3	7
3	8
3	9
3	10
3	11
4	1
4	2
4	3
4	4
5	1
5	12
5	2
5	3
5	4
5	5
5	6
5	7
5	8
5	9
5	10
5	11
6	1
6	12
6	2
6	3
6	4
6	5
6	6
6	7
6	8
6	9
6	10
6	11
7	1
7	2
7	3
7	4
7	5
7	6
7	7
7	8
7	9
7	10
7	11
7	12
\.


--
-- TOC entry 5146 (class 0 OID 16844)
-- Dependencies: 220
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departments (department_id, department_code, department_name) FROM stdin;
1	QA	QA
2	QC	QC
3	LAB_SOP	Lab SOP
5	WH	Warehouse
6	SALES	Sales
7	SCALE	Scale Department
4	LAB_ECOPHOS	ECOPHOS LAB
11	QC_ECOPHOS	QC ECOPHOS
12	QC_SOP	QC SOP
13	EXEC	Executive Office
\.


--
-- TOC entry 5179 (class 0 OID 17102)
-- Dependencies: 254
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5165 (class 0 OID 17002)
-- Dependencies: 240
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	plants	department
8	plants	orgposition
9	plants	plant
10	plants	role
11	accounts	userprofile
12	production	bigbag
13	production	customer
14	production	orderbatch
15	production	productionbatch
16	production	productionrun
17	production	sackconversion
18	production	sacktype
19	production	silo
\.


--
-- TOC entry 5163 (class 0 OID 16994)
-- Dependencies: 238
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-21 11:56:33.89703+03
2	auth	0001_initial	2026-07-21 11:56:34.064029+03
3	admin	0001_initial	2026-07-21 11:56:34.113627+03
4	admin	0002_logentry_remove_auto_add	2026-07-21 11:56:34.12344+03
5	admin	0003_logentry_add_action_flag_choices	2026-07-21 11:56:34.140438+03
6	contenttypes	0002_remove_content_type_name	2026-07-21 11:56:34.177073+03
7	auth	0002_alter_permission_name_max_length	2026-07-21 11:56:34.191854+03
8	auth	0003_alter_user_email_max_length	2026-07-21 11:56:34.203868+03
9	auth	0004_alter_user_username_opts	2026-07-21 11:56:34.218071+03
10	auth	0005_alter_user_last_login_null	2026-07-21 11:56:34.231429+03
11	auth	0006_require_contenttypes_0002	2026-07-21 11:56:34.236707+03
12	auth	0007_alter_validators_add_error_messages	2026-07-21 11:56:34.259237+03
13	auth	0008_alter_user_username_max_length	2026-07-21 11:56:34.28432+03
14	auth	0009_alter_user_last_name_max_length	2026-07-21 11:56:34.296355+03
15	auth	0010_alter_group_name_max_length	2026-07-21 11:56:34.315862+03
16	auth	0011_update_proxy_permissions	2026-07-21 11:56:34.329582+03
17	auth	0012_alter_user_first_name_max_length	2026-07-21 11:56:34.345486+03
18	sessions	0001_initial	2026-07-21 11:56:34.368079+03
19	plants	0001_initial	2026-07-21 22:20:01.23102+03
20	plants	0002_phase_and_org_updates	2026-07-21 22:29:55.90344+03
21	accounts	0001_initial	2026-07-22 00:13:05.528702+03
22	production	0001_initial	2026-07-22 18:00:27.251305+03
\.


--
-- TOC entry 5180 (class 0 OID 17130)
-- Dependencies: 255
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
57t3a96136zr8pw2jxcqqu283otjedsb	.eJxVjDEOwjAMAP_iGUWhOHHSkb1vqGzH0AJqpaadEH9HlTrAene6N_S8rUO_VVv6sUALDZx-mbA-bdpFefB0n53O07qM4vbEHba6bi72uh7t32DgOkALwopGOWcL5CN68bmgWqKYsrdATdJLNMR8DnRDxcQkqZAQspGiwOcL0-U3ng:1wm6dR:uBDBSh6OWW1ke9vZbr6aRkF5HQ17sBIxgQi8pOM2_gg	2026-08-04 12:19:33.220098+03
9huoscuhdl1sut6w2i2miknaes8491uy	.eJxVjDEOwjAMAP_iGUVO0qS0IztvqOzYkAJKpKadEH9HlTrAene6N0y0rXnami7TLDCChdMvY0pPLbuQB5V7NamWdZnZ7Ik5bDPXKvq6HO3fIFPLMEJHQkjYJw0YNQ7ihcmRGxhRKLFHDtbjTc_i0XfReqZAMYi1g7pe4fMF-_I4LQ:1wm6mT:0nAqD7eLMw7Ku_WlL4ayj8yXWvf_4LUXIRM1cPCPrZs	2026-08-04 12:28:53.373698+03
cs4cvq4pvzw68tsacd9dq95n2ejefjkg	.eJxVjDEOwjAMAP_iGUVO0qS0IztvqOzYkAJKpKadEH9HlTrAene6N0y0rXnami7TLDCChdMvY0pPLbuQB5V7NamWdZnZ7Ik5bDPXKvq6HO3fIFPLMEJHQkjYJw0YNQ7ihcmRGxhRKLFHDtbjTc_i0XfReqZAMYi1g7pe4fMF-_I4LQ:1wmGBy:bzIJTbaWLsIIP_iWE_VHScyoMaW4w_y8hcz47gVqhCE	2026-08-04 22:31:50.696092+03
\.


--
-- TOC entry 5161 (class 0 OID 16952)
-- Dependencies: 235
-- Data for Name: employee_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_assignments (assignment_id, employee_id, position_id, shift_mode, group_id, fixed_shift_type_id, start_date, end_date, is_current) FROM stdin;
\.


--
-- TOC entry 5159 (class 0 OID 16942)
-- Dependencies: 233
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (employee_id, full_name, national_id, phone, hire_date, is_active) FROM stdin;
\.


--
-- TOC entry 5151 (class 0 OID 16879)
-- Dependencies: 225
-- Data for Name: org_positions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.org_positions (position_id, entity_type, plant_id, department_id, role_id, hierarchy_level) FROM stdin;
1	plant	1	\N	1	1
2	plant	1	\N	2	2
3	plant	1	\N	3	3
4	plant	1	\N	4	4
5	plant	1	\N	5	5
6	plant	2	\N	1	1
7	plant	2	\N	2	2
8	plant	2	\N	3	3
9	plant	2	\N	4	4
10	plant	2	\N	5	5
11	plant	3	\N	1	1
12	plant	3	\N	2	2
13	plant	3	\N	3	3
14	plant	3	\N	4	4
15	plant	3	\N	5	5
16	plant	4	\N	1	1
17	plant	4	\N	2	2
18	plant	4	\N	3	3
19	plant	4	\N	4	4
20	plant	4	\N	5	5
21	plant	5	\N	1	1
22	plant	5	\N	2	2
23	plant	5	\N	3	3
24	plant	5	\N	4	4
25	plant	5	\N	5	5
26	plant	6	\N	1	1
27	plant	6	\N	2	2
28	plant	6	\N	3	3
29	plant	6	\N	4	4
30	plant	6	\N	5	5
31	plant	7	\N	1	1
32	plant	7	\N	2	2
33	plant	7	\N	3	3
34	plant	7	\N	4	4
35	plant	7	\N	5	5
36	plant	8	\N	1	1
37	plant	8	\N	2	2
38	plant	8	\N	3	3
39	plant	8	\N	4	4
40	plant	8	\N	5	5
41	plant	9	\N	1	1
42	plant	9	\N	2	2
43	plant	9	\N	3	3
44	plant	9	\N	4	4
45	plant	9	\N	5	5
46	plant	10	\N	1	1
47	plant	10	\N	2	2
48	plant	10	\N	3	3
49	plant	10	\N	4	4
50	plant	10	\N	5	5
51	plant	11	\N	1	1
52	plant	11	\N	2	2
53	plant	11	\N	3	3
54	plant	11	\N	4	4
55	plant	11	\N	5	5
56	plant	12	\N	1	1
57	plant	12	\N	2	2
58	plant	12	\N	3	3
59	plant	12	\N	4	4
60	plant	12	\N	5	5
61	department	\N	1	2	2
62	department	\N	1	3	3
63	department	\N	1	4	4
64	department	\N	1	5	5
65	department	\N	1	6	1
66	department	\N	2	2	2
67	department	\N	2	3	3
68	department	\N	2	4	4
69	department	\N	2	5	5
70	department	\N	2	6	1
71	department	\N	3	2	2
72	department	\N	3	3	3
73	department	\N	3	4	4
74	department	\N	3	5	5
75	department	\N	3	7	1
76	department	\N	4	2	2
77	department	\N	4	3	3
78	department	\N	4	4	4
79	department	\N	4	5	5
80	department	\N	4	7	1
81	department	\N	5	2	2
82	department	\N	5	3	3
83	department	\N	5	5	5
84	department	\N	5	8	1
85	department	\N	5	9	4
86	department	\N	6	2	2
87	department	\N	6	5	4
88	department	\N	6	10	1
89	department	\N	6	11	3
90	plant	1	\N	13	6
91	plant	2	\N	13	6
92	plant	3	\N	13	6
93	plant	4	\N	13	6
94	plant	5	\N	13	6
95	plant	6	\N	13	6
96	plant	7	\N	13	6
97	plant	8	\N	13	6
98	plant	9	\N	13	6
99	plant	10	\N	13	6
100	plant	11	\N	13	6
101	plant	12	\N	13	6
102	department	\N	1	12	6
103	department	\N	2	12	6
104	department	\N	1	13	7
105	department	\N	2	13	7
106	department	\N	3	13	6
107	department	\N	4	13	6
108	department	\N	5	13	6
109	department	\N	6	13	5
110	department	\N	7	2	2
111	department	\N	7	3	3
112	department	\N	7	5	4
113	department	\N	7	6	1
114	department	\N	7	13	5
115	plant	1	\N	13	6
116	plant	2	\N	13	6
117	plant	3	\N	13	6
118	plant	4	\N	13	6
119	plant	5	\N	13	6
120	plant	6	\N	13	6
121	plant	7	\N	13	6
122	plant	8	\N	13	6
123	plant	9	\N	13	6
124	plant	10	\N	13	6
125	plant	11	\N	13	6
126	plant	12	\N	13	6
127	department	\N	1	12	6
128	department	\N	2	12	6
129	department	\N	1	13	7
130	department	\N	2	13	7
131	department	\N	3	13	6
132	department	\N	4	13	6
133	department	\N	5	13	6
134	department	\N	6	13	5
135	department	\N	7	13	5
136	department	\N	7	2	2
137	department	\N	7	3	3
138	department	\N	7	5	4
139	department	\N	7	6	1
141	department	\N	13	22	0
142	department	\N	13	23	0
143	department	\N	13	24	1
144	department	\N	13	25	1
145	department	\N	13	26	1
146	department	\N	13	27	1
\.


--
-- TOC entry 5144 (class 0 OID 16833)
-- Dependencies: 218
-- Data for Name: plants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plants (plant_id, plant_code, plant_name, phase) FROM stdin;
1	DCP	DCP	1
2	GCC1	GCC1	1
3	GCC2	GCC2	1
4	PA	PA	1
5	SA200	SA 200	3
6	SA600	SA 600	3
7	SOPA	SOP A	2
8	SOPB	SOP B	2
9	SOPC	SOP C	2
10	SOPD	SOP D	2
11	SOPH	SOP H	2
12	GSOP	G SOP	2
\.


--
-- TOC entry 5190 (class 0 OID 17183)
-- Dependencies: 265
-- Data for Name: production_bigbag; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_bigbag (id, bag_number, status, packed_at, production_batch_id) FROM stdin;
\.


--
-- TOC entry 5184 (class 0 OID 17160)
-- Dependencies: 259
-- Data for Name: production_customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_customer (id, name, is_export) FROM stdin;
\.


--
-- TOC entry 5196 (class 0 OID 17213)
-- Dependencies: 271
-- Data for Name: production_orderbatch; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_orderbatch (id, order_reference, total_weight_kg, dispatched_at, customer_id) FROM stdin;
\.


--
-- TOC entry 5200 (class 0 OID 17227)
-- Dependencies: 275
-- Data for Name: production_orderbatch_sack_conversions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_orderbatch_sack_conversions (id, orderbatch_id, sackconversion_id) FROM stdin;
\.


--
-- TOC entry 5198 (class 0 OID 17221)
-- Dependencies: 273
-- Data for Name: production_orderbatch_whole_big_bags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_orderbatch_whole_big_bags (id, orderbatch_id, bigbag_id) FROM stdin;
\.


--
-- TOC entry 5186 (class 0 OID 17166)
-- Dependencies: 261
-- Data for Name: production_productionbatch; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_productionbatch (id, sequence_number, produced_at, production_run_id, silo_id) FROM stdin;
\.


--
-- TOC entry 5192 (class 0 OID 17192)
-- Dependencies: 267
-- Data for Name: production_productionrun; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_productionrun (id, run_number, started_at, ended_at, is_closed, plant_id) FROM stdin;
\.


--
-- TOC entry 5194 (class 0 OID 17204)
-- Dependencies: 269
-- Data for Name: production_sackconversion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_sackconversion (id, sack_count, converted_at, big_bag_id, sack_type_id) FROM stdin;
\.


--
-- TOC entry 5188 (class 0 OID 17175)
-- Dependencies: 263
-- Data for Name: production_sacktype; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_sacktype (id, name, nominal_weight_kg) FROM stdin;
\.


--
-- TOC entry 5202 (class 0 OID 17233)
-- Dependencies: 277
-- Data for Name: production_silo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.production_silo (id, code, plant_id) FROM stdin;
\.


--
-- TOC entry 5148 (class 0 OID 16855)
-- Dependencies: 222
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (role_id, role_name) FROM stdin;
12	QC Specialist
13	Technician
1	Production Manager
2	Section Head
3	Shift Leader
4	Chemist
5	Supervisor
6	Department Manager
7	Lab Manager
8	Warehouse Manager
9	Storekeeper
10	Sales Manager
11	Responsible Engineer
22	CEO
23	Deputy CEO
24	Head of Quality Sector
25	Head of ECOPHOS Production Sector
26	Head of SOP Production Sector
27	Head of SA Production Sector
\.


--
-- TOC entry 5157 (class 0 OID 16938)
-- Dependencies: 231
-- Data for Name: rotation_reference; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rotation_reference (reference_date) FROM stdin;
2026-07-20
\.


--
-- TOC entry 5155 (class 0 OID 16914)
-- Dependencies: 229
-- Data for Name: shift_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shift_groups (group_id, group_name) FROM stdin;
1	A
2	B
3	C
4	D
\.


--
-- TOC entry 5156 (class 0 OID 16922)
-- Dependencies: 230
-- Data for Name: shift_rotation_pattern; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shift_rotation_pattern (group_id, day_offset, shift_type_id) FROM stdin;
1	4	5
1	5	5
1	2	4
1	3	4
1	0	3
1	1	3
1	6	2
1	7	2
2	2	5
2	3	5
2	0	4
2	1	4
2	6	3
2	7	3
2	4	2
2	5	2
3	6	5
3	7	5
3	4	4
3	5	4
3	2	3
3	3	3
3	0	2
3	1	2
4	0	5
4	1	5
4	6	4
4	7	4
4	4	3
4	5	3
4	2	2
4	3	2
\.


--
-- TOC entry 5153 (class 0 OID 16905)
-- Dependencies: 227
-- Data for Name: shift_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shift_types (shift_type_id, shift_type_name, start_time, end_time) FROM stdin;
1	نهاري	08:00:00	16:00:00
2	أولى	08:00:00	16:00:00
3	ثانية	16:00:00	00:00:00
4	ثالثة	00:00:00	08:00:00
5	إجازة	\N	\N
\.


--
-- TOC entry 5216 (class 0 OID 0)
-- Dependencies: 256
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_userprofile_id_seq', 1, false);


--
-- TOC entry 5217 (class 0 OID 0)
-- Dependencies: 243
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5218 (class 0 OID 0)
-- Dependencies: 245
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5219 (class 0 OID 0)
-- Dependencies: 241
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- TOC entry 5220 (class 0 OID 0)
-- Dependencies: 249
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5221 (class 0 OID 0)
-- Dependencies: 247
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- TOC entry 5222 (class 0 OID 0)
-- Dependencies: 251
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5223 (class 0 OID 0)
-- Dependencies: 219
-- Name: departments_department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departments_department_id_seq', 13, true);


--
-- TOC entry 5224 (class 0 OID 0)
-- Dependencies: 253
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5225 (class 0 OID 0)
-- Dependencies: 239
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- TOC entry 5226 (class 0 OID 0)
-- Dependencies: 237
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- TOC entry 5227 (class 0 OID 0)
-- Dependencies: 234
-- Name: employee_assignments_assignment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_assignments_assignment_id_seq', 1, false);


--
-- TOC entry 5228 (class 0 OID 0)
-- Dependencies: 232
-- Name: employees_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_employee_id_seq', 1, false);


--
-- TOC entry 5229 (class 0 OID 0)
-- Dependencies: 224
-- Name: org_positions_position_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.org_positions_position_id_seq', 146, true);


--
-- TOC entry 5230 (class 0 OID 0)
-- Dependencies: 217
-- Name: plants_plant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plants_plant_id_seq', 12, true);


--
-- TOC entry 5231 (class 0 OID 0)
-- Dependencies: 264
-- Name: production_bigbag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_bigbag_id_seq', 1, false);


--
-- TOC entry 5232 (class 0 OID 0)
-- Dependencies: 258
-- Name: production_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_customer_id_seq', 1, false);


--
-- TOC entry 5233 (class 0 OID 0)
-- Dependencies: 270
-- Name: production_orderbatch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_orderbatch_id_seq', 1, false);


--
-- TOC entry 5234 (class 0 OID 0)
-- Dependencies: 274
-- Name: production_orderbatch_sack_conversions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_orderbatch_sack_conversions_id_seq', 1, false);


--
-- TOC entry 5235 (class 0 OID 0)
-- Dependencies: 272
-- Name: production_orderbatch_whole_big_bags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_orderbatch_whole_big_bags_id_seq', 1, false);


--
-- TOC entry 5236 (class 0 OID 0)
-- Dependencies: 260
-- Name: production_productionbatch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_productionbatch_id_seq', 1, false);


--
-- TOC entry 5237 (class 0 OID 0)
-- Dependencies: 266
-- Name: production_productionrun_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_productionrun_id_seq', 1, false);


--
-- TOC entry 5238 (class 0 OID 0)
-- Dependencies: 268
-- Name: production_sackconversion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_sackconversion_id_seq', 1, false);


--
-- TOC entry 5239 (class 0 OID 0)
-- Dependencies: 262
-- Name: production_sacktype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_sacktype_id_seq', 1, false);


--
-- TOC entry 5240 (class 0 OID 0)
-- Dependencies: 276
-- Name: production_silo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.production_silo_id_seq', 1, false);


--
-- TOC entry 5241 (class 0 OID 0)
-- Dependencies: 221
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 27, true);


--
-- TOC entry 5242 (class 0 OID 0)
-- Dependencies: 228
-- Name: shift_groups_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shift_groups_group_id_seq', 4, true);


--
-- TOC entry 5243 (class 0 OID 0)
-- Dependencies: 226
-- Name: shift_types_shift_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shift_types_shift_type_id_seq', 5, true);


--
-- TOC entry 4909 (class 2606 OID 17145)
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 17147)
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- TOC entry 4873 (class 2606 OID 17128)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4878 (class 2606 OID 17059)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4881 (class 2606 OID 17028)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4875 (class 2606 OID 17020)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 17050)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4870 (class 2606 OID 17014)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 17042)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 17074)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4883 (class 2606 OID 17034)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4895 (class 2606 OID 17048)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 17088)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4886 (class 2606 OID 17123)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4835 (class 2606 OID 16867)
-- Name: department_plant_scope department_plant_scope_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_plant_scope
    ADD CONSTRAINT department_plant_scope_pkey PRIMARY KEY (department_id, plant_id);


--
-- TOC entry 4825 (class 2606 OID 16851)
-- Name: departments departments_department_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_department_code_key UNIQUE (department_code);


--
-- TOC entry 4827 (class 2606 OID 16853)
-- Name: departments departments_department_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_department_name_key UNIQUE (department_name);


--
-- TOC entry 4829 (class 2606 OID 16849)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (department_id);


--
-- TOC entry 4901 (class 2606 OID 17109)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4863 (class 2606 OID 17008)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4865 (class 2606 OID 17006)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4861 (class 2606 OID 17000)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 17136)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4857 (class 2606 OID 16961)
-- Name: employee_assignments employee_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_assignments
    ADD CONSTRAINT employee_assignments_pkey PRIMARY KEY (assignment_id);


--
-- TOC entry 4853 (class 2606 OID 16950)
-- Name: employees employees_national_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_national_id_key UNIQUE (national_id);


--
-- TOC entry 4855 (class 2606 OID 16948)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (employee_id);


--
-- TOC entry 4839 (class 2606 OID 16888)
-- Name: org_positions org_positions_entity_type_plant_id_department_id_role_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.org_positions
    ADD CONSTRAINT org_positions_entity_type_plant_id_department_id_role_id_key UNIQUE (entity_type, plant_id, department_id, role_id);


--
-- TOC entry 4841 (class 2606 OID 16886)
-- Name: org_positions org_positions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.org_positions
    ADD CONSTRAINT org_positions_pkey PRIMARY KEY (position_id);


--
-- TOC entry 4819 (class 2606 OID 16838)
-- Name: plants plants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT plants_pkey PRIMARY KEY (plant_id);


--
-- TOC entry 4821 (class 2606 OID 16840)
-- Name: plants plants_plant_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT plants_plant_code_key UNIQUE (plant_code);


--
-- TOC entry 4823 (class 2606 OID 16842)
-- Name: plants plants_plant_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plants
    ADD CONSTRAINT plants_plant_name_key UNIQUE (plant_name);


--
-- TOC entry 4926 (class 2606 OID 17190)
-- Name: production_bigbag production_bigbag_bag_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_bigbag
    ADD CONSTRAINT production_bigbag_bag_number_key UNIQUE (bag_number);


--
-- TOC entry 4928 (class 2606 OID 17188)
-- Name: production_bigbag production_bigbag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_bigbag
    ADD CONSTRAINT production_bigbag_pkey PRIMARY KEY (id);


--
-- TOC entry 4913 (class 2606 OID 17164)
-- Name: production_customer production_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_customer
    ADD CONSTRAINT production_customer_pkey PRIMARY KEY (id);


--
-- TOC entry 4943 (class 2606 OID 17219)
-- Name: production_orderbatch production_orderbatch_order_reference_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch
    ADD CONSTRAINT production_orderbatch_order_reference_key UNIQUE (order_reference);


--
-- TOC entry 4945 (class 2606 OID 17217)
-- Name: production_orderbatch production_orderbatch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch
    ADD CONSTRAINT production_orderbatch_pkey PRIMARY KEY (id);


--
-- TOC entry 4953 (class 2606 OID 17292)
-- Name: production_orderbatch_sack_conversions production_orderbatch_sa_orderbatch_id_sackconver_6ef22cff_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_sack_conversions
    ADD CONSTRAINT production_orderbatch_sa_orderbatch_id_sackconver_6ef22cff_uniq UNIQUE (orderbatch_id, sackconversion_id);


--
-- TOC entry 4956 (class 2606 OID 17231)
-- Name: production_orderbatch_sack_conversions production_orderbatch_sack_conversions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_sack_conversions
    ADD CONSTRAINT production_orderbatch_sack_conversions_pkey PRIMARY KEY (id);


--
-- TOC entry 4947 (class 2606 OID 17278)
-- Name: production_orderbatch_whole_big_bags production_orderbatch_wh_orderbatch_id_bigbag_id_d6d80dc5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_whole_big_bags
    ADD CONSTRAINT production_orderbatch_wh_orderbatch_id_bigbag_id_d6d80dc5_uniq UNIQUE (orderbatch_id, bigbag_id);


--
-- TOC entry 4951 (class 2606 OID 17225)
-- Name: production_orderbatch_whole_big_bags production_orderbatch_whole_big_bags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_whole_big_bags
    ADD CONSTRAINT production_orderbatch_whole_big_bags_pkey PRIMARY KEY (id);


--
-- TOC entry 4915 (class 2606 OID 17171)
-- Name: production_productionbatch production_productionbatch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_productionbatch
    ADD CONSTRAINT production_productionbatch_pkey PRIMARY KEY (id);


--
-- TOC entry 4918 (class 2606 OID 17173)
-- Name: production_productionbatch production_productionbatch_sequence_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_productionbatch
    ADD CONSTRAINT production_productionbatch_sequence_number_key UNIQUE (sequence_number);


--
-- TOC entry 4931 (class 2606 OID 17197)
-- Name: production_productionrun production_productionrun_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_productionrun
    ADD CONSTRAINT production_productionrun_pkey PRIMARY KEY (id);


--
-- TOC entry 4934 (class 2606 OID 17251)
-- Name: production_productionrun production_productionrun_plant_id_run_number_518ed2ae_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_productionrun
    ADD CONSTRAINT production_productionrun_plant_id_run_number_518ed2ae_uniq UNIQUE (plant_id, run_number);


--
-- TOC entry 4936 (class 2606 OID 17211)
-- Name: production_sackconversion production_sackconversion_big_bag_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_sackconversion
    ADD CONSTRAINT production_sackconversion_big_bag_id_key UNIQUE (big_bag_id);


--
-- TOC entry 4938 (class 2606 OID 17209)
-- Name: production_sackconversion production_sackconversion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_sackconversion
    ADD CONSTRAINT production_sackconversion_pkey PRIMARY KEY (id);


--
-- TOC entry 4922 (class 2606 OID 17181)
-- Name: production_sacktype production_sacktype_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_sacktype
    ADD CONSTRAINT production_sacktype_name_key UNIQUE (name);


--
-- TOC entry 4924 (class 2606 OID 17179)
-- Name: production_sacktype production_sacktype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_sacktype
    ADD CONSTRAINT production_sacktype_pkey PRIMARY KEY (id);


--
-- TOC entry 4959 (class 2606 OID 17237)
-- Name: production_silo production_silo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_silo
    ADD CONSTRAINT production_silo_pkey PRIMARY KEY (id);


--
-- TOC entry 4962 (class 2606 OID 17306)
-- Name: production_silo production_silo_plant_id_code_468cbc3a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_silo
    ADD CONSTRAINT production_silo_plant_id_code_468cbc3a_uniq UNIQUE (plant_id, code);


--
-- TOC entry 4831 (class 2606 OID 16860)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4833 (class 2606 OID 16862)
-- Name: roles roles_role_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);


--
-- TOC entry 4847 (class 2606 OID 16921)
-- Name: shift_groups shift_groups_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_groups
    ADD CONSTRAINT shift_groups_group_name_key UNIQUE (group_name);


--
-- TOC entry 4849 (class 2606 OID 16919)
-- Name: shift_groups shift_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_groups
    ADD CONSTRAINT shift_groups_pkey PRIMARY KEY (group_id);


--
-- TOC entry 4851 (class 2606 OID 16927)
-- Name: shift_rotation_pattern shift_rotation_pattern_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_rotation_pattern
    ADD CONSTRAINT shift_rotation_pattern_pkey PRIMARY KEY (group_id, day_offset);


--
-- TOC entry 4843 (class 2606 OID 16910)
-- Name: shift_types shift_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_types
    ADD CONSTRAINT shift_types_pkey PRIMARY KEY (shift_type_id);


--
-- TOC entry 4845 (class 2606 OID 16912)
-- Name: shift_types shift_types_shift_type_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_types
    ADD CONSTRAINT shift_types_shift_type_name_key UNIQUE (shift_type_name);


--
-- TOC entry 4907 (class 1259 OID 17158)
-- Name: accounts_userprofile_org_position_id_855e6222; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_userprofile_org_position_id_855e6222 ON public.accounts_userprofile USING btree (org_position_id);


--
-- TOC entry 4871 (class 1259 OID 17129)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4876 (class 1259 OID 17070)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4879 (class 1259 OID 17071)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4866 (class 1259 OID 17056)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4887 (class 1259 OID 17086)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4890 (class 1259 OID 17085)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4893 (class 1259 OID 17100)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4896 (class 1259 OID 17099)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4884 (class 1259 OID 17124)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4899 (class 1259 OID 17120)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4902 (class 1259 OID 17121)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4903 (class 1259 OID 17138)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4906 (class 1259 OID 17137)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4858 (class 1259 OID 16984)
-- Name: idx_assignments_employee; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_assignments_employee ON public.employee_assignments USING btree (employee_id);


--
-- TOC entry 4859 (class 1259 OID 16985)
-- Name: idx_assignments_position; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_assignments_position ON public.employee_assignments USING btree (position_id);


--
-- TOC entry 4836 (class 1259 OID 16983)
-- Name: idx_positions_department; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_positions_department ON public.org_positions USING btree (department_id);


--
-- TOC entry 4837 (class 1259 OID 16982)
-- Name: idx_positions_plant; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_positions_plant ON public.org_positions USING btree (plant_id);


--
-- TOC entry 4929 (class 1259 OID 17249)
-- Name: production_bigbag_production_batch_id_ff181fe4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_bigbag_production_batch_id_ff181fe4 ON public.production_bigbag USING btree (production_batch_id);


--
-- TOC entry 4940 (class 1259 OID 17276)
-- Name: production_orderbatch_customer_id_068c5672; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_orderbatch_customer_id_068c5672 ON public.production_orderbatch USING btree (customer_id);


--
-- TOC entry 4941 (class 1259 OID 17275)
-- Name: production_orderbatch_order_reference_f8c9d912_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_orderbatch_order_reference_f8c9d912_like ON public.production_orderbatch USING btree (order_reference varchar_pattern_ops);


--
-- TOC entry 4954 (class 1259 OID 17303)
-- Name: production_orderbatch_sack_conversions_orderbatch_id_4aeec03f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_orderbatch_sack_conversions_orderbatch_id_4aeec03f ON public.production_orderbatch_sack_conversions USING btree (orderbatch_id);


--
-- TOC entry 4957 (class 1259 OID 17304)
-- Name: production_orderbatch_sack_sackconversion_id_07b6f0b5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_orderbatch_sack_sackconversion_id_07b6f0b5 ON public.production_orderbatch_sack_conversions USING btree (sackconversion_id);


--
-- TOC entry 4948 (class 1259 OID 17290)
-- Name: production_orderbatch_whole_big_bags_bigbag_id_715a299a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_orderbatch_whole_big_bags_bigbag_id_715a299a ON public.production_orderbatch_whole_big_bags USING btree (bigbag_id);


--
-- TOC entry 4949 (class 1259 OID 17289)
-- Name: production_orderbatch_whole_big_bags_orderbatch_id_fbb9ffb5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_orderbatch_whole_big_bags_orderbatch_id_fbb9ffb5 ON public.production_orderbatch_whole_big_bags USING btree (orderbatch_id);


--
-- TOC entry 4916 (class 1259 OID 17258)
-- Name: production_productionbatch_production_run_id_dec49a9e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_productionbatch_production_run_id_dec49a9e ON public.production_productionbatch USING btree (production_run_id);


--
-- TOC entry 4919 (class 1259 OID 17313)
-- Name: production_productionbatch_silo_id_c9b68b4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_productionbatch_silo_id_c9b68b4e ON public.production_productionbatch USING btree (silo_id);


--
-- TOC entry 4932 (class 1259 OID 17257)
-- Name: production_productionrun_plant_id_3252c6d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_productionrun_plant_id_3252c6d7 ON public.production_productionrun USING btree (plant_id);


--
-- TOC entry 4939 (class 1259 OID 17269)
-- Name: production_sackconversion_sack_type_id_aa3df867; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_sackconversion_sack_type_id_aa3df867 ON public.production_sackconversion USING btree (sack_type_id);


--
-- TOC entry 4920 (class 1259 OID 17243)
-- Name: production_sacktype_name_bade1752_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_sacktype_name_bade1752_like ON public.production_sacktype USING btree (name varchar_pattern_ops);


--
-- TOC entry 4960 (class 1259 OID 17312)
-- Name: production_silo_plant_id_122d9eb2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX production_silo_plant_id_122d9eb2 ON public.production_silo USING btree (plant_id);


--
-- TOC entry 4983 (class 2606 OID 17148)
-- Name: accounts_userprofile accounts_userprofile_org_position_id_855e6222_fk_org_posit; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_org_position_id_855e6222_fk_org_posit FOREIGN KEY (org_position_id) REFERENCES public.org_positions(position_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4984 (class 2606 OID 17153)
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4975 (class 2606 OID 17065)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4976 (class 2606 OID 17060)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4974 (class 2606 OID 17051)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4977 (class 2606 OID 17080)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4978 (class 2606 OID 17075)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4979 (class 2606 OID 17094)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4980 (class 2606 OID 17089)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4963 (class 2606 OID 16868)
-- Name: department_plant_scope department_plant_scope_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_plant_scope
    ADD CONSTRAINT department_plant_scope_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(department_id) ON DELETE CASCADE;


--
-- TOC entry 4964 (class 2606 OID 16873)
-- Name: department_plant_scope department_plant_scope_plant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_plant_scope
    ADD CONSTRAINT department_plant_scope_plant_id_fkey FOREIGN KEY (plant_id) REFERENCES public.plants(plant_id) ON DELETE CASCADE;


--
-- TOC entry 4981 (class 2606 OID 17110)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4982 (class 2606 OID 17115)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4970 (class 2606 OID 16962)
-- Name: employee_assignments employee_assignments_employee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_assignments
    ADD CONSTRAINT employee_assignments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id) ON DELETE CASCADE;


--
-- TOC entry 4971 (class 2606 OID 16977)
-- Name: employee_assignments employee_assignments_fixed_shift_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_assignments
    ADD CONSTRAINT employee_assignments_fixed_shift_type_id_fkey FOREIGN KEY (fixed_shift_type_id) REFERENCES public.shift_types(shift_type_id);


--
-- TOC entry 4972 (class 2606 OID 16972)
-- Name: employee_assignments employee_assignments_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_assignments
    ADD CONSTRAINT employee_assignments_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.shift_groups(group_id);


--
-- TOC entry 4973 (class 2606 OID 16967)
-- Name: employee_assignments employee_assignments_position_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_assignments
    ADD CONSTRAINT employee_assignments_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.org_positions(position_id) ON DELETE CASCADE;


--
-- TOC entry 4965 (class 2606 OID 16894)
-- Name: org_positions org_positions_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.org_positions
    ADD CONSTRAINT org_positions_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(department_id) ON DELETE CASCADE;


--
-- TOC entry 4966 (class 2606 OID 16889)
-- Name: org_positions org_positions_plant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.org_positions
    ADD CONSTRAINT org_positions_plant_id_fkey FOREIGN KEY (plant_id) REFERENCES public.plants(plant_id) ON DELETE CASCADE;


--
-- TOC entry 4967 (class 2606 OID 16899)
-- Name: org_positions org_positions_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.org_positions
    ADD CONSTRAINT org_positions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- TOC entry 4987 (class 2606 OID 17244)
-- Name: production_bigbag production_bigbag_production_batch_id_ff181fe4_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_bigbag
    ADD CONSTRAINT production_bigbag_production_batch_id_ff181fe4_fk_productio FOREIGN KEY (production_batch_id) REFERENCES public.production_productionbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4992 (class 2606 OID 17284)
-- Name: production_orderbatch_whole_big_bags production_orderbatc_bigbag_id_715a299a_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_whole_big_bags
    ADD CONSTRAINT production_orderbatc_bigbag_id_715a299a_fk_productio FOREIGN KEY (bigbag_id) REFERENCES public.production_bigbag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4991 (class 2606 OID 17270)
-- Name: production_orderbatch production_orderbatc_customer_id_068c5672_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch
    ADD CONSTRAINT production_orderbatc_customer_id_068c5672_fk_productio FOREIGN KEY (customer_id) REFERENCES public.production_customer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4994 (class 2606 OID 17293)
-- Name: production_orderbatch_sack_conversions production_orderbatc_orderbatch_id_4aeec03f_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_sack_conversions
    ADD CONSTRAINT production_orderbatc_orderbatch_id_4aeec03f_fk_productio FOREIGN KEY (orderbatch_id) REFERENCES public.production_orderbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4993 (class 2606 OID 17279)
-- Name: production_orderbatch_whole_big_bags production_orderbatc_orderbatch_id_fbb9ffb5_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_whole_big_bags
    ADD CONSTRAINT production_orderbatc_orderbatch_id_fbb9ffb5_fk_productio FOREIGN KEY (orderbatch_id) REFERENCES public.production_orderbatch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4995 (class 2606 OID 17298)
-- Name: production_orderbatch_sack_conversions production_orderbatc_sackconversion_id_07b6f0b5_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_orderbatch_sack_conversions
    ADD CONSTRAINT production_orderbatc_sackconversion_id_07b6f0b5_fk_productio FOREIGN KEY (sackconversion_id) REFERENCES public.production_sackconversion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4985 (class 2606 OID 17198)
-- Name: production_productionbatch production_productio_production_run_id_dec49a9e_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_productionbatch
    ADD CONSTRAINT production_productio_production_run_id_dec49a9e_fk_productio FOREIGN KEY (production_run_id) REFERENCES public.production_productionrun(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4986 (class 2606 OID 17238)
-- Name: production_productionbatch production_productio_silo_id_c9b68b4e_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_productionbatch
    ADD CONSTRAINT production_productio_silo_id_c9b68b4e_fk_productio FOREIGN KEY (silo_id) REFERENCES public.production_silo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4988 (class 2606 OID 17252)
-- Name: production_productionrun production_productionrun_plant_id_3252c6d7_fk_plants_plant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_productionrun
    ADD CONSTRAINT production_productionrun_plant_id_3252c6d7_fk_plants_plant_id FOREIGN KEY (plant_id) REFERENCES public.plants(plant_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4989 (class 2606 OID 17259)
-- Name: production_sackconversion production_sackconve_big_bag_id_10f5d157_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_sackconversion
    ADD CONSTRAINT production_sackconve_big_bag_id_10f5d157_fk_productio FOREIGN KEY (big_bag_id) REFERENCES public.production_bigbag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4990 (class 2606 OID 17264)
-- Name: production_sackconversion production_sackconve_sack_type_id_aa3df867_fk_productio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_sackconversion
    ADD CONSTRAINT production_sackconve_sack_type_id_aa3df867_fk_productio FOREIGN KEY (sack_type_id) REFERENCES public.production_sacktype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4996 (class 2606 OID 17307)
-- Name: production_silo production_silo_plant_id_122d9eb2_fk_plants_plant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.production_silo
    ADD CONSTRAINT production_silo_plant_id_122d9eb2_fk_plants_plant_id FOREIGN KEY (plant_id) REFERENCES public.plants(plant_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4968 (class 2606 OID 16928)
-- Name: shift_rotation_pattern shift_rotation_pattern_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_rotation_pattern
    ADD CONSTRAINT shift_rotation_pattern_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.shift_groups(group_id) ON DELETE CASCADE;


--
-- TOC entry 4969 (class 2606 OID 16933)
-- Name: shift_rotation_pattern shift_rotation_pattern_shift_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shift_rotation_pattern
    ADD CONSTRAINT shift_rotation_pattern_shift_type_id_fkey FOREIGN KEY (shift_type_id) REFERENCES public.shift_types(shift_type_id);


-- Completed on 2026-07-22 18:41:49

--
-- PostgreSQL database dump complete
--


