services:
  db:
    image: postgres:15-alpine
    container_name: chemflow_db
    restart: always
    environment:
      - POSTGRES_DB=chemflow_db
      - POSTGRES_USER=chemflow_user
      - POSTGRES_PASSWORD=ChemFlowSecure2026!!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: chemflow_redis
    ports:
      - "6379:6379"
  web:
    build: ./backend
    container_name: chemflow_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=chemflow_db
      - DB_USER=chemflow_user
      - DB_PASSWORD=ChemFlowSecure2026!!
    depends_on:
      - db
      - redis
  pgadmin:
    image: dpage/pgadmin4
    container_name: chemflow_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@chemflow.com
      - PGADMIN_DEFAULT_PASSWORD=Admin2026!
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data:
