# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("factory", "0026_ton_lab_sample"),
        ("finished_products", "0001_initial"),
        ("plants", "0007_rename_plant_code_to_product_type"),
        ("shared_definitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_code", models.CharField(max_length=30, unique=True)),
                ("customer_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("payment_terms", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "orders_customers",
                "ordering": ["customer_name"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quotation_number", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("valid_until", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="orders.customer",
                    ),
                ),
            ],
            options={
                "db_table": "orders_quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "packaging_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="factory.packingtype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finished_products.product",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "orders_quotation_lines",
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("customer_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("stock_reserved", "Stock Reserved"),
                            ("partially_delivered", "Partially Delivered"),
                            ("fully_delivered", "Fully Delivered"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "grade_policy",
                    models.CharField(
                        choices=[
                            ("any", "Open — any grade within same classification"),
                            ("fixed", "Fixed on specific grade"),
                            ("open_at_packing", "Determined at packing time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "batch_source",
                    models.CharField(
                        choices=[
                            ("production", "From Production"),
                            ("warehouse", "From Warehouse"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("unit", models.CharField(default="tons", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="orders.customer",
                    ),
                ),
                (
                    "fixed_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_sales_orders",
                        to="factory.grade",
                    ),
                ),
                (
                    "product_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="shared_definitions.qualitygrade",
                    ),
                ),
            ],
            options={
                "db_table": "sales_orders",
            },
        ),
        migrations.CreateModel(
            name="OrderPlantAllocationChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_reallocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_logs_from",
                        to="plants.plant",
                    ),
                ),
                (
                    "to_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_logs_to",
                        to="plants.plant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_logs",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_plant_allocation_change_log",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("handover", "Handover to Warehouse"),
                            ("staging", "Staging"),
                            ("loading", "Loading"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_movements",
                        to="factory.grade",
                    ),
                ),
                (
                    "source_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_movements_out",
                        to="plants.plant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_movements",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.salesorder",
                    ),
                ),
                (
                    "packaging_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="factory.packingtype",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="plants.plant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finished_products.product",
                    ),
                ),
            ],
            options={
                "db_table": "orders_sales_order_lines",
            },
        ),
        migrations.CreateModel(
            name="SalesPriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_type", models.CharField(blank=True, max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "packaging_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="factory.packingtype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finished_products.product",
                    ),
                ),
            ],
            options={
                "db_table": "orders_price_lists",
            },
        ),
        migrations.CreateModel(
            name="OrderPlantAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_allocations",
                        to="plants.plant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_allocations",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_plant_allocations",
                "unique_together": {("order", "plant")},
            },
        ),
    ]
