# Generated by Django 5.0.2 on 2026-08-05 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("factory", "0002_grade_qualityconformityresult_grade"),
        ("plants", "0006_alter_orgpositiondepartmentscope_options"),
        ("shared_definitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("customer_name", models.CharField(max_length=150)),
                (
                    "grade_policy",
                    models.CharField(
                        choices=[
                            ("any", "مفتوحة - أي جريد داخل نفس التصنيف"),
                            ("fixed", "مقفولة على جريد واحد بالتحديد"),
                            ("open_at_packing", "بتتحدد لحظة التعبئة"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "batch_source",
                    models.CharField(
                        choices=[
                            ("production", "من الإنتاج"),
                            ("warehouse", "من المخزن"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("unit", models.CharField(default="tons", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fixed_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_sales_orders",
                        to="factory.grade",
                    ),
                ),
                (
                    "product_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="shared_definitions.qualitygrade",
                    ),
                ),
            ],
            options={
                "db_table": "sales_orders",
            },
        ),
        migrations.CreateModel(
            name="OrderPlantAllocationChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_reallocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_logs_from",
                        to="plants.plant",
                    ),
                ),
                (
                    "to_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_logs_to",
                        to="plants.plant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_logs",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_plant_allocation_change_log",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("production", "إنتاج"),
                            ("handover", "تسليم للمخزن"),
                            ("staging", "تجهيز"),
                            ("loading", "تحميل"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_movements",
                        to="factory.grade",
                    ),
                ),
                (
                    "source_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_movements_out",
                        to="plants.plant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_movements",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderPlantAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_allocations",
                        to="plants.plant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_allocations",
                        to="orders.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "order_plant_allocations",
                "unique_together": {("order", "plant")},
            },
        ),
    ]
