# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finished_products", "0001_initial"),
        ("lab", "0001_initial"),
        ("plants", "0007_rename_plant_code_to_product_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_code", models.CharField(max_length=30, unique=True)),
                ("material_name", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=50)),
                ("subcategory", models.CharField(blank=True, max_length=50)),
                ("unit", models.CharField(max_length=20)),
                (
                    "minimum_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "reorder_point",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("inspection_required", models.BooleanField(default=True)),
                ("inspection_template", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "products",
                    models.ManyToManyField(blank=True, to="finished_products.product"),
                ),
            ],
            options={
                "db_table": "packaging_materials",
                "ordering": ["material_name"],
            },
        ),
        migrations.CreateModel(
            name="PackagingReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warehouse_qty", models.DecimalField(decimal_places=3, max_digits=10)),
                ("factory_qty", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("matched", "Matched"), ("variance", "Variance")],
                        max_length=10,
                    ),
                ),
                ("reconciled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packaging.packagingmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "packaging_reconciliation",
                "ordering": ["-reconciled_at"],
            },
        ),
        migrations.CreateModel(
            name="PackagingStockLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_type", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("status", models.CharField(max_length=20)),
                ("reference_text", models.CharField(blank=True, max_length=200)),
                ("occurred_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="packaging.packagingmaterial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "packaging_stock_ledger",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="PackagingSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_code", models.CharField(max_length=30, unique=True)),
                ("supplier_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "materials_supplied",
                    models.ManyToManyField(
                        blank=True, to="packaging.packagingmaterial"
                    ),
                ),
            ],
            options={
                "db_table": "packaging_suppliers",
                "ordering": ["supplier_name"],
            },
        ),
        migrations.CreateModel(
            name="PackagingReceiving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiving_number", models.CharField(max_length=30, unique=True)),
                ("date", models.DateField()),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quarantine", "Quarantine"),
                            ("available", "Available"),
                            ("rejected", "Rejected"),
                        ],
                        default="quarantine",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lab.sample",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_records",
                        to="packaging.packagingmaterial",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packaging_receiving",
                        to="finished_products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_records",
                        to="packaging.packagingsupplier",
                    ),
                ),
            ],
            options={
                "db_table": "packaging_receiving",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PackingOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "quantity_waste",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "quantity_remaining",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("operated_at", models.DateTimeField()),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="plants.plant"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="packaging.packagingmaterial",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finished_products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "packing_operations",
                "ordering": ["-operated_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acceptance_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("rejection_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("quality_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="packaging.packagingsupplier",
                    ),
                ),
            ],
            options={
                "db_table": "packaging_supplier_evaluations",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.CreateModel(
            name="FactoryPackagingStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packaging_stock",
                        to="plants.plant",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factory_stocks",
                        to="packaging.packagingmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "factory_packaging_stock",
                "unique_together": {("factory", "material")},
            },
        ),
        migrations.CreateModel(
            name="PackagingStockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="packaging.packagingmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "packaging_stock_balances",
                "unique_together": {("material", "status")},
            },
        ),
    ]
