# Generated by Django 5.0.2 on 2026-08-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0003_departmentplantscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_code", models.CharField(max_length=20, unique=True)),
                ("material_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "materials",
                "ordering": ["material_name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_code", models.CharField(max_length=20, unique=True)),
                ("supplier_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "suppliers",
                "ordering": ["supplier_name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_code", models.CharField(max_length=30, unique=True)),
                ("storage_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "allow_estimated_issue",
                    models.BooleanField(
                        default=False,
                        help_text="يسمح بتسجيل عمليات صرف تقديرية (Estimated) من المخزن ده بدل الدقيقة بس",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storages",
                        to="raw_materials.material",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_storages",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "material_storages",
                "ordering": ["plant", "material", "storage_name"],
                "unique_together": {("plant", "material", "storage_name")},
            },
        ),
        migrations.CreateModel(
            name="MaterialTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_code", models.CharField(max_length=30, unique=True)),
                ("test_name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="raw_materials.material",
                    ),
                ),
            ],
            options={
                "db_table": "material_tests",
                "ordering": ["material", "test_name"],
            },
        ),
        migrations.CreateModel(
            name="RawMaterialDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=30)),
                ("weight_tons", models.DecimalField(decimal_places=3, max_digits=8)),
                ("arrived_at", models.DateTimeField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accepted", "مقبولة"),
                            ("rejected", "مرفوضة"),
                            ("accepted_with_deduction", "مقبولة بخصم"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "deduction_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="raw_materials.material",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_material_deliveries",
                        to="plants.plant",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="raw_materials.materialstorage",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="raw_materials.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "raw_material_deliveries",
                "ordering": ["-arrived_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "إضافة"),
                            ("out", "صرف"),
                            ("adjustment", "تسوية"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "accuracy_type",
                    models.CharField(
                        choices=[("exact", "دقيق"), ("estimated", "تقديري")],
                        default="exact",
                        max_length=20,
                    ),
                ),
                ("quantity_tons", models.DecimalField(decimal_places=3, max_digits=12)),
                ("transaction_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="plants.plant",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="raw_materials.material",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="raw_materials.materialstorage",
                    ),
                ),
                (
                    "reference_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to="raw_materials.rawmaterialdelivery",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="RawMaterialLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_number", models.CharField(max_length=50, unique=True)),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="raw_materials.rawmaterialdelivery",
                    ),
                ),
            ],
            options={
                "db_table": "raw_material_lots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawMaterialSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_stage",
                    models.CharField(
                        choices=[
                            ("receipt", "عند الاستلام"),
                            ("pre_milling", "قبل الطحن"),
                            ("post_milling", "بعد الطحن"),
                        ],
                        default="receipt",
                        max_length=15,
                    ),
                ),
                ("sample_number", models.PositiveIntegerField()),
                ("sampled_at", models.DateTimeField()),
                ("sampled_by", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        help_text="إجباري بس لو المرحلة (عند الاستلام)، فاضي في حالة قبل/بعد الطحن",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="raw_materials.rawmaterialdelivery",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="samples",
                        to="raw_materials.material",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_material_samples",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "raw_material_samples",
                "ordering": ["sampled_at"],
                "unique_together": {
                    ("plant", "material", "sample_stage", "sample_number")
                },
            },
        ),
        migrations.CreateModel(
            name="MaterialSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "specification_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="raw_materials.material",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="raw_materials.materialtest",
                    ),
                ),
            ],
            options={
                "db_table": "material_specifications",
                "ordering": ["material", "test"],
                "unique_together": {("material", "test")},
            },
        ),
        migrations.CreateModel(
            name="RawMaterialAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_conforming", models.BooleanField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="raw_materials.materialtest",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="raw_materials.rawmaterialsample",
                    ),
                ),
            ],
            options={
                "db_table": "raw_material_analysis",
                "ordering": ["sample", "test"],
                "unique_together": {("sample", "test")},
            },
        ),
    ]
