# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0007_rename_plant_code_to_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "custom_permissions_screens",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ScreenColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField()),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="custom_permissions.screen",
                    ),
                ),
            ],
            options={
                "db_table": "custom_permissions_screen_columns",
                "ordering": ["screen", "order"],
                "unique_together": {("screen", "code")},
            },
        ),
        migrations.CreateModel(
            name="ColumnPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("view", "View Only"),
                            ("edit", "View & Edit"),
                        ],
                        default="hidden",
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_permissions",
                        to="plants.role",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="custom_permissions.screencolumn",
                    ),
                ),
            ],
            options={
                "db_table": "custom_permissions_column_permissions",
                "unique_together": {("column", "role")},
            },
        ),
    ]
