# Generated by Django 5.0.2 on 2026-08-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("plants", "0003_departmentplantscope"),
        ("shared_definitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConformityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_conformity_rules",
                        to="plants.plant",
                    ),
                ),
                (
                    "quality_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conformity_rules",
                        to="shared_definitions.qualitygrade",
                    ),
                ),
            ],
            options={
                "db_table": "factory_conformity_rules",
            },
        ),
        migrations.CreateModel(
            name="OutputPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_output_points",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_output_points",
                "unique_together": {("plant", "code")},
            },
        ),
        migrations.CreateModel(
            name="PackingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_packing_locations",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_packing_locations",
                "unique_together": {("plant", "name")},
            },
        ),
        migrations.CreateModel(
            name="OutputReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sampled_at", models.DateTimeField()),
                (
                    "sample_code",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "output_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="factory.outputpoint",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_output_readings",
                        to="plants.plant",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="بتتحدد تلقائيًا من الوردية الثابتة بتاعة المستخدم، والأدمن يقدر يعدّلها وقت الحاجة",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factory_output_readings",
                        to="employees.shifttype",
                    ),
                ),
                (
                    "packing_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="readings",
                        to="factory.packinglocation",
                    ),
                ),
            ],
            options={
                "db_table": "factory_output_readings",
                "ordering": ["-sampled_at"],
            },
        ),
        migrations.CreateModel(
            name="PackingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_packing_types",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_packing_types",
                "unique_together": {("plant", "name")},
            },
        ),
        migrations.CreateModel(
            name="PackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(default="tons", max_length=20)),
                ("packed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "output_reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packing_events",
                        to="factory.outputreading",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_packing_events",
                        to="plants.plant",
                    ),
                ),
                (
                    "packing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packing_events",
                        to="factory.packingtype",
                    ),
                ),
            ],
            options={
                "db_table": "factory_packing_events",
                "ordering": ["-packed_at"],
            },
        ),
        migrations.CreateModel(
            name="PackingConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(default="tons", max_length=20)),
                ("converted_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_packing_conversions",
                        to="plants.plant",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions_out",
                        to="factory.packingevent",
                    ),
                ),
                (
                    "target_packing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversions_in",
                        to="factory.packingtype",
                    ),
                ),
            ],
            options={
                "db_table": "factory_packing_conversions",
                "ordering": ["-converted_at"],
            },
        ),
        migrations.AddField(
            model_name="outputreading",
            name="packing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="readings",
                to="factory.packingtype",
            ),
        ),
        migrations.CreateModel(
            name="ProcessStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_process_stages",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_process_stages",
                "unique_together": {("plant", "code")},
            },
        ),
        migrations.CreateModel(
            name="ProcessReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sampled_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_process_readings",
                        to="plants.plant",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="factory.processstage",
                    ),
                ),
            ],
            options={
                "db_table": "factory_process_readings",
                "ordering": ["-sampled_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityConformityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "conformity_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="factory.conformityrule",
                    ),
                ),
                (
                    "quality_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conformity_results",
                        to="shared_definitions.qualitygrade",
                    ),
                ),
                (
                    "reading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conformity",
                        to="factory.outputreading",
                    ),
                ),
            ],
            options={
                "db_table": "factory_quality_conformity_results",
            },
        ),
        migrations.CreateModel(
            name="TestDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("chemical", "كيميائي"), ("physical", "فيزيائي")],
                        max_length=15,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_test_definitions",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_test_definitions",
                "unique_together": {("plant", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProcessStageTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_tests",
                        to="factory.processstage",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_stage_links",
                        to="factory.testdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "factory_process_stage_tests",
                "unique_together": {("stage", "test")},
            },
        ),
        migrations.CreateModel(
            name="ProcessAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="factory.processreading",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="process_results",
                        to="factory.testdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "factory_process_analysis_results",
                "unique_together": {("reading", "test")},
            },
        ),
        migrations.CreateModel(
            name="OutputPointTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_tests",
                        to="factory.outputpoint",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_point_links",
                        to="factory.testdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "factory_output_point_tests",
                "unique_together": {("output_point", "test")},
            },
        ),
        migrations.CreateModel(
            name="OutputAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="factory.outputreading",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="output_results",
                        to="factory.testdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "factory_output_analysis_results",
                "unique_together": {("reading", "test")},
            },
        ),
    ]
