# Generated by Django 5.0.2 on 2026-08-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0001_initial"),
        ("plants", "0006_alter_orgpositiondepartmentscope_options"),
        ("shared_definitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="shared_definitions.qualitygrade",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_grades",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_grades",
                "unique_together": {("plant", "code")},
            },
        ),
        migrations.AddField(
            model_name="qualityconformityresult",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conformity_results",
                to="factory.grade",
            ),
        ),
    ]
