# Generated by Django 5.0.2 on 2026-08-05 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("factory", "0002_grade_qualityconformityresult_grade"),
        ("plants", "0006_alter_orgpositiondepartmentscope_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conformityrule",
            unique_together={("plant", "name")},
        ),
        migrations.CreateModel(
            name="PlantLotSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_mode",
                    models.CharField(
                        choices=[
                            ("auto", "توليد أوتوماتيكي"),
                            ("manual", "إدخال يدوي من إدارة محددة"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "reset_threshold",
                    models.IntegerField(
                        default=9999,
                        help_text="لما الرقم التسلسلي يوصل للرقم ده، الدورة (Cycle) بتزيد واحد والتسلسل يرجع لـ 1",
                    ),
                ),
                ("current_cycle", models.IntegerField(default=1)),
                ("current_sequence", models.IntegerField(default=0)),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_setting",
                        to="plants.plant",
                    ),
                ),
                (
                    "sampling_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="الإدارة المسؤولة عن سحب العينات لهذا المصنع",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lot_sampling_plants",
                        to="plants.department",
                    ),
                ),
            ],
            options={
                "db_table": "factory_plant_lot_settings",
            },
        ),
        migrations.CreateModel(
            name="Ton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_number", models.IntegerField()),
                ("sequence_number", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("production_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tons",
                        to="plants.plant",
                    ),
                ),
                (
                    "production_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tons",
                        to="employees.shifttype",
                    ),
                ),
            ],
            options={
                "db_table": "factory_tons",
                "unique_together": {("plant", "cycle_number", "sequence_number")},
            },
        ),
        migrations.CreateModel(
            name="RepresentativeSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_number", models.IntegerField()),
                ("code", models.CharField(blank=True, max_length=150)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative_samples",
                        to="plants.plant",
                    ),
                ),
                (
                    "tons",
                    models.ManyToManyField(
                        related_name="representative_samples", to="factory.ton"
                    ),
                ),
            ],
            options={
                "db_table": "factory_representative_samples",
            },
        ),
        migrations.CreateModel(
            name="TonGradeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ton_grade_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ton_assignments",
                        to="factory.grade",
                    ),
                ),
                (
                    "ton",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_assignment",
                        to="factory.ton",
                    ),
                ),
            ],
            options={
                "db_table": "factory_ton_grade_assignments",
            },
        ),
        migrations.CreateModel(
            name="SampleChemicalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_overridden", models.BooleanField(default=False)),
                (
                    "representative_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemical_results",
                        to="factory.representativesample",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sample_chemical_results",
                        to="factory.testdefinition",
                    ),
                ),
                (
                    "ton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemical_results",
                        to="factory.ton",
                    ),
                ),
            ],
            options={
                "db_table": "factory_sample_chemical_results",
                "unique_together": {("ton", "test")},
            },
        ),
        migrations.CreateModel(
            name="TonPhysicalResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ton_physical_results",
                        to="factory.testdefinition",
                    ),
                ),
                (
                    "ton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_results",
                        to="factory.ton",
                    ),
                ),
            ],
            options={
                "db_table": "factory_ton_physical_results",
                "unique_together": {("ton", "test")},
            },
        ),
    ]
