# Generated by Django 5.0.2 on 2026-08-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "factory",
            "0003_alter_conformityrule_unique_together_plantlotsetting_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantlotsetting",
            name="reset_threshold",
            field=models.IntegerField(default=9999),
        ),
    ]
