# Generated by Django 5.0.2 on 2026-08-08 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0004_alter_plantlotsetting_reset_threshold"),
        ("plants", "0007_rename_plant_code_to_product_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactoryPlant",
            fields=[],
            options={
                "verbose_name": "Plant (مصنع)",
                "verbose_name_plural": "Plants (مصانع)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plants.plant",),
        ),
        migrations.AddField(
            model_name="outputreading",
            name="analyzed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples_analyzed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outputreading",
            name="product_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="outputreading",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="ممكن يتحدد بعدين لما التحليل يخلص، مش لازم وقت السحب",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outputreading",
            name="sampled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ton",
            name="output_reading",
            field=models.ForeignKey(
                blank=True,
                help_text="العينة اللي الطن ده جزء منها",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tons",
                to="factory.outputreading",
            ),
        ),
        migrations.CreateModel(
            name="FloorStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in_production", "دخول - إنتاج"),
                            ("out_handover", "خروج - تسليم للمخزن"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_stock_movements",
                        to="factory.grade",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_stock_movements",
                        to="plants.plant",
                    ),
                ),
                (
                    "ton",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_stock_movements",
                        to="factory.ton",
                    ),
                ),
            ],
            options={
                "db_table": "factory_floor_stock_movements",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="FloorStockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_stock_balances",
                        to="factory.grade",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_stock_balances",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_floor_stock_balances",
                "unique_together": {("plant", "grade")},
            },
        ),
    ]
