# Generated by Django 5.0.2 on 2026-08-09 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0005_factoryplant_outputreading_analyzed_by_and_more"),
        ("plants", "0007_rename_plant_code_to_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("local", "سبب محلي"),
                            ("non_conforming", "سبب غير مطابق"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_reasons",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_grade_reasons",
            },
        ),
        migrations.AddField(
            model_name="tongradeassignment",
            name="reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grade_assignments",
                to="factory.gradereason",
            ),
        ),
        migrations.CreateModel(
            name="RepresentativeGroupSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_group_size", models.PositiveIntegerField(default=4)),
                (
                    "packing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_size_settings",
                        to="factory.packingtype",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_size_settings",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_representative_group_sizes",
                "unique_together": {("plant", "packing_type")},
            },
        ),
    ]
