# Generated by Django 5.0.2 on 2026-08-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0006_gradereason_tongradeassignment_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdefinition",
            name="scope",
            field=models.CharField(
                choices=[
                    ("reaction", "التفاعل (Reaction)"),
                    ("final_product", "المنتج النهائي (Final Product)"),
                ],
                default="final_product",
                max_length=20,
            ),
        ),
    ]
