# Generated by Django 5.0.2 on 2026-08-11 03:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("factory", "0008_remove_floorstockmovement_grade_and_more"),
        ("plants", "0007_rename_plant_code_to_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputreading",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="outputreading",
            name="sample_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="packingconversion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packingconversion",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="packingevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="qualityconformityresult",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tongradeassignment",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="outputreading",
            name="output_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="readings",
                to="factory.outputpoint",
            ),
        ),
        migrations.AlterField(
            model_name="outputreading",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                db_column="shift_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factory_output_readings",
                to="employees.shifttype",
            ),
        ),
        migrations.AlterField(
            model_name="packingevent",
            name="output_reading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packing_events",
                to="factory.outputreading",
            ),
        ),
        migrations.AlterField(
            model_name="ton",
            name="production_shift",
            field=models.ForeignKey(
                blank=True,
                db_column="production_shift_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factory_tons",
                to="employees.shifttype",
            ),
        ),
        migrations.CreateModel(
            name="FloorStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("in", "إضافة"), ("out", "سحب")], max_length=10
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("occurred_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_stock_movements",
                        to="factory.grade",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_floor_stock_movements",
                        to="plants.plant",
                    ),
                ),
                (
                    "ton",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="floor_stock_movements",
                        to="factory.ton",
                    ),
                ),
            ],
            options={
                "db_table": "factory_floor_stock_movements",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="FloorStockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_stock_balances",
                        to="factory.grade",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_floor_stock_balances",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "factory_floor_stock_balances",
                "unique_together": {("plant", "grade")},
            },
        ),
    ]
