# Generated by Django 5.0.2 on 2026-08-12 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0009_outputreading_notes_outputreading_sample_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="outputreading",
            name="lab_shift_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factory_readings_lab_shift_head",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
