# Generated by Django 5.0.2 on 2026-08-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0010_outputreading_lab_shift_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="معرف فريد بالإنجليزي بدون مسافات، يستخدم داخليًا (مثال: batch_number)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="الاسم اللي هيظهر للمستخدم", max_length=100
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("number", "رقم عشري"),
                            ("integer", "رقم صحيح"),
                            ("text", "نص"),
                            ("date", "تاريخ"),
                            ("choice", "اختيار من قائمة"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "أساسي (وزن / كمية)"),
                            ("chemical", "فحص كيميائي"),
                            ("physical", "فحص فيزيائي"),
                            ("general", "بيانات عامة"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="لنوع 'اختيار من قائمة' فقط - قائمة بالخيارات",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "factory_field_definitions",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackingTypeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_type_configs",
                        to="factory.fielddefinition",
                    ),
                ),
                (
                    "packing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_configs",
                        to="factory.packingtype",
                    ),
                ),
            ],
            options={
                "db_table": "factory_packing_type_fields",
                "ordering": ["order"],
                "unique_together": {("packing_type", "field")},
            },
        ),
    ]
