# Generated by Django 5.0.2 on 2026-08-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_processstage_order_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المرحلة'),
        ),
    ]
