# Generated by Django 5.0.2 on 2026-08-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0016_drop_processstage_code_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="الجريد الأساسي الذي يتبع له هذا الثانوي (اتركه فارغاً إذا كان الجريد أساسياً)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="factory.grade",
            ),
        ),
        migrations.AddField(
            model_name="ton",
            name="status",
            field=models.CharField(
                choices=[
                    ("under_test", "تحت الاختبار (لم يُسحب)"),
                    ("sampled", "تم سحب العينة"),
                    ("graded", "أخذ الجريد"),
                ],
                default="under_test",
                help_text="حالة الطن: تحت الاختبار حتى تُسحب العينة وتظهر النتيجة",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="tongradeassignment",
            name="grade",
        ),
        migrations.AddField(
            model_name="tongradeassignment",
            name="primary_grade",
            field=models.ForeignKey(
                help_text="الجريد الأساسي (تصدير / محلي / غير مطابق)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ton_primary_assignments",
                to="factory.grade",
            ),
        ),
        migrations.AddField(
            model_name="tongradeassignment",
            name="secondary_grade",
            field=models.ForeignKey(
                blank=True,
                help_text="الجريد الثانوي التابع للأساسي (اختياري)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ton_secondary_assignments",
                to="factory.grade",
            ),
        ),
        migrations.AddField(
            model_name="floorstockbalance",
            name="status",
            field=models.CharField(
                choices=[
                    ("graded", "أخذ الجريد"),
                    ("waiting_not_sampled", "في انتظار الجريد (لم يُسحب للمعمل)"),
                    ("waiting_sampled", "في انتظار الجريد (تم السحب للمعمل)"),
                ],
                default="graded",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="floorstockmovement",
            name="status",
            field=models.CharField(
                choices=[
                    ("graded", "أخذ الجريد"),
                    ("waiting_not_sampled", "في انتظار الجريد (لم يُسحب للمعمل)"),
                    ("waiting_sampled", "في انتظار الجريد (تم السحب للمعمل)"),
                ],
                default="graded",
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="floorstockbalance",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="floorstockbalance",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                help_text='الجريد فقط لقسم "أخذ الجريد"، يبقى فارغاً للأقسام المنتظرة',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_stock_balances",
                to="factory.grade",
            ),
        ),
        migrations.AlterField(
            model_name="floorstockmovement",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_stock_movements",
                to="factory.grade",
            ),
        ),
        migrations.AddConstraint(
            model_name="floorstockbalance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "graded")),
                fields=("plant", "grade", "status"),
                name="uniq_floorstock_plant_grade_graded",
            ),
        ),
        migrations.AddConstraint(
            model_name="floorstockbalance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["waiting_not_sampled", "waiting_sampled"])),
                fields=("plant", "status"),
                name="uniq_floorstock_plant_waiting_status",
            ),
        ),
    ]
