# Generated by Django 5.0.2 on 2026-08-14 18:22

from django.db import migrations, models


def forwards(apps, schema_editor):
    TestDefinition = apps.get_model("factory", "TestDefinition")
    for td in TestDefinition.objects.all():
        old_scope = td.scope
        td.scopes = [old_scope] if old_scope else []
        td.save(update_fields=["scopes"])


def backwards(apps, schema_editor):
    TestDefinition = apps.get_model("factory", "TestDefinition")
    for td in TestDefinition.objects.all():
        scopes = td.scopes or []
        td.scope = scopes[0] if scopes else "final_product"
        td.save(update_fields=["scope"])


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_alter_tongradeassignment_primary_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdefinition',
            name='scopes',
            field=models.JSONField(default=list, verbose_name='النطاقات'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='testdefinition',
            name='scope',
        ),
    ]
