# Generated by Django 5.0.2 on 2026-08-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_testdefinition_scopes_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='parent',
        ),
    ]
