# Generated by Django 5.0.2 on 2026-08-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0020_remove_grade_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('primary', 'أساسي'), ('secondary', 'ثانوي')], default='primary', help_text='أساسي = يظهر في عمود الجريد الأساسي، ثانوي = يظهر في عمود الجريد الثانوي', max_length=10, verbose_name='نوع الجريد'),
        ),
    ]
