# Generated by Django 5.0.2 on 2026-08-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0021_grade_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='classification',
        ),
    ]
