# Generated by Django 5.0.2 on 2026-08-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0022_remove_grade_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingtype',
            options={'ordering': ['id']},
        ),
    ]
