# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0025_conformityrule_max_value_conformityrule_min_value_and_more"),
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ton",
            name="lab_sample",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factory_ton",
                to="lab.sample",
            ),
        ),
    ]
