# Generated by Django 5.0.2 on 2026-07-29 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0003_departmentplantscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactionTankReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tank_code",
                    models.CharField(
                        choices=[
                            ("t102", "T102 (خزان الهضم)"),
                            ("t103", "T103 (بعد إزالة الرمل)"),
                            ("t104", "T104 (نقطة فحص موازية)"),
                            ("t150", "T150 (خزان الفلتريت)"),
                            ("t151", "T151 (خزان CaCl2 المركز)"),
                            ("t152_ab", "T152 (A & B)"),
                            ("t152_cd", "T152 (C & D)"),
                            ("belt", "Belt (حزام الوزن)"),
                            ("mixer", "Mixer (المخلط المستمر)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sampled_at", models.DateTimeField()),
                (
                    "ph",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fluoride_ppm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "solid_content_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "p2o5_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tss_ppm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "cacl2_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "mc_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "transferred_to_gcc2_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dcp_reaction_readings",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "dcp_reaction_tank_readings",
                "ordering": ["-sampled_at"],
            },
        ),
    ]
