# Generated by Django 5.0.2 on 2026-07-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcp", "0001_initial"),
        ("plants", "0003_departmentplantscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalProductSiloReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "silo",
                    models.CharField(
                        choices=[("a", "سيلو A"), ("b", "سيلو B"), ("c", "سيلو C")],
                        max_length=1,
                    ),
                ),
                ("sampled_at", models.DateTimeField()),
                ("sample_code", models.CharField(blank=True, max_length=20)),
                (
                    "represented_weight_tons",
                    models.DecimalField(decimal_places=2, default=4, max_digits=6),
                ),
                (
                    "mc_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "p2o5_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fluoride_ppm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cl_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bulk_density",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "total_ca_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dcp_final_silo_readings",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "dcp_final_silo_readings",
                "ordering": ["-sampled_at"],
            },
        ),
        migrations.CreateModel(
            name="FinalProductPacking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "packing_method",
                    models.CharField(
                        choices=[
                            ("big_bag", "تعبئة Big Bag مباشرة"),
                            ("sack_direct", "تعبئة شكاير مباشرة من الخط"),
                            ("sack_from_bigbag", "إعادة تعبئة شكاير من Big Bag"),
                        ],
                        max_length=20,
                    ),
                ),
                ("packed_at", models.DateTimeField()),
                (
                    "quantity_tons",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("bags_count", models.PositiveIntegerField(blank=True, null=True)),
                ("post_pack_sample_taken", models.BooleanField(default=False)),
                ("post_pack_sample_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dcp_final_packings",
                        to="plants.plant",
                    ),
                ),
                (
                    "source_silo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packings",
                        to="dcp.finalproductsiloreading",
                    ),
                ),
            ],
            options={
                "db_table": "dcp_final_packings",
                "ordering": ["-packed_at"],
            },
        ),
    ]
