# Generated by Django 5.0.2 on 2026-07-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcp", "0002_finalproductsiloreading_finalproductpacking"),
        ("plants", "0003_departmentplantscope"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finalproductpacking",
            name="packing_method",
        ),
        migrations.AddField(
            model_name="finalproductpacking",
            name="container_type",
            field=models.CharField(
                choices=[
                    ("big_bag", "Big Bag"),
                    ("small_bag", "شكارة صغيرة"),
                    ("bulk", "Bulk"),
                ],
                default="big_bag",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="finalproductsiloreading",
            name="cumulative_weight_tons",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="finalproductsiloreading",
            name="sequence_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="اسيبه فاضي عشان يتحسب تلقائي (بيتصفر كل 10,000 طن)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="finalproductsiloreading",
            name="sample_code",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.CreateModel(
            name="FinalProductRepacking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("packed_at", models.DateTimeField()),
                (
                    "quantity_tons",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("bags_count", models.PositiveIntegerField(blank=True, null=True)),
                ("post_pack_sample_taken", models.BooleanField(default=False)),
                ("post_pack_sample_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dcp_final_repackings",
                        to="plants.plant",
                    ),
                ),
                (
                    "source_packing",
                    models.ForeignKey(
                        limit_choices_to={"container_type": "big_bag"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repackings",
                        to="dcp.finalproductpacking",
                    ),
                ),
            ],
            options={
                "db_table": "dcp_final_repackings",
                "ordering": ["-packed_at"],
            },
        ),
        migrations.CreateModel(
            name="FinalProductSampleLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_number", models.PositiveIntegerField()),
                (
                    "color_status",
                    models.CharField(
                        choices=[
                            ("present", "موجود"),
                            ("slight", "موجود بنسبة بسيطة"),
                            ("absent", "غير موجود"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "im_status",
                    models.CharField(
                        choices=[
                            ("present", "موجود"),
                            ("slight", "موجود بنسبة بسيطة"),
                            ("absent", "غير موجود"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "over_status",
                    models.CharField(
                        choices=[
                            ("present", "موجود"),
                            ("slight", "موجود بنسبة بسيطة"),
                            ("absent", "غير موجود"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "silo_reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="dcp.finalproductsiloreading",
                    ),
                ),
            ],
            options={
                "db_table": "dcp_final_sample_lots",
                "ordering": ["lot_number"],
                "unique_together": {("silo_reading", "lot_number")},
            },
        ),
    ]
