# Generated by Django 5.0.2 on 2026-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcp", "0003_remove_finalproductpacking_packing_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalproductsiloreading",
            name="sequence_number",
            field=models.CharField(
                blank=True,
                help_text="اسيبه فاضي عشان يتحسب تلقائي (بيتصفر كل 10,000 طن)",
                max_length=100,
                null=True,
            ),
        ),
    ]
