# Generated by Django 5.0.2 on 2026-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcp", "0004_alter_finalproductsiloreading_sequence_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalproductsiloreading",
            name="represented_weight_tons",
            field=models.PositiveIntegerField(
                default=4, help_text="الوزن بأرقام صحيحة فقط بدون كسور"
            ),
        ),
        migrations.AlterField(
            model_name="finalproductsiloreading",
            name="sequence_number",
            field=models.CharField(
                blank=True, help_text="كود الممثلة التلقائي", max_length=100, null=True
            ),
        ),
    ]
