# Generated by Django 5.0.2 on 2026-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcp", "0005_alter_finalproductsiloreading_represented_weight_tons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalproductsamplelot",
            name="qafeez_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("green_yellow", "Green & Yellow"),
                    ("blue", "Blue"),
                    ("white", "White"),
                    ("red", "Red"),
                ],
                max_length=15,
                verbose_name="لون القفيز",
            ),
        ),
    ]
