# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("factory", "0025_conformityrule_max_value_conformityrule_min_value_and_more"),
        ("lab", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggested_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conform", "Conform"),
                            ("conform_with_deduction", "Conform with Deduction"),
                            ("reject", "Reject"),
                            ("hold", "Hold"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        choices=[
                            ("conform", "Conform"),
                            ("conform_with_deduction", "Conform with Deduction"),
                            ("reject", "Reject"),
                            ("hold", "Hold"),
                        ],
                        max_length=30,
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_decision",
                        to="lab.sample",
                    ),
                ),
                (
                    "suggested_by_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="factory.conformityrule",
                    ),
                ),
            ],
            options={
                "db_table": "quality_control_decisions",
            },
        ),
    ]
