# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0007_rename_plant_code_to_product_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=30, unique=True)),
                ("item_name", models.CharField(max_length=150)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("subcategory", models.CharField(blank=True, max_length=50)),
                ("unit", models.CharField(max_length=20)),
                (
                    "minimum_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "reorder_point",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spare_parts",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "db_table": "spare_part_items",
                "ordering": ["item_name"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_number", models.CharField(max_length=30, unique=True)),
                ("date", models.DateField()),
                ("supplier_name", models.CharField(blank=True, max_length=150)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.CharField(default="received", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_vouchers",
                        to="spare_parts.sparepartitem",
                    ),
                ),
            ],
            options={
                "db_table": "spare_part_receiving_vouchers",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="IssueVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_number", models.CharField(max_length=30, unique=True)),
                ("date", models.DateField()),
                ("issued_to", models.CharField(blank=True, max_length=150)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("purpose", models.TextField(blank=True)),
                ("status", models.CharField(default="issued", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_vouchers",
                        to="spare_parts.sparepartitem",
                    ),
                ),
            ],
            options={
                "db_table": "spare_part_issue_vouchers",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SparePartStockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "available",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "on_loan",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "in_maintenance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_balance",
                        to="spare_parts.sparepartitem",
                    ),
                ),
            ],
            options={
                "db_table": "spare_part_stock_balances",
            },
        ),
        migrations.CreateModel(
            name="SparePartStockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receiving", "Receiving"),
                            ("issuing", "Issuing"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("count", "Physical Count"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("reference_text", models.CharField(blank=True, max_length=200)),
                ("occurred_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to="spare_parts.sparepartitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "spare_part_stock_transactions",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_date", models.DateField()),
                (
                    "system_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "physical_quantity",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("counted_by", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_counts",
                        to="spare_parts.sparepartitem",
                    ),
                ),
            ],
            options={
                "db_table": "spare_part_stock_counts",
                "ordering": ["-count_date"],
            },
        ),
    ]
