# Generated by Django 5.0.2 on 2026-07-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                (
                    "national_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "employees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeAssignment",
            fields=[
                ("assignment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "shift_mode",
                    models.CharField(
                        choices=[
                            ("rotating", "مدوّر مع مجموعة"),
                            ("fixed", "وردية ثابتة"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "employee_assignments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RotationReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_date", models.DateField()),
            ],
            options={
                "db_table": "rotation_reference",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShiftGroup",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=5, unique=True)),
            ],
            options={
                "db_table": "shift_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShiftRotationPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_offset", models.IntegerField()),
            ],
            options={
                "db_table": "shift_rotation_pattern",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                ("shift_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("shift_type_name", models.CharField(max_length=20, unique=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "shift_types",
                "managed": False,
            },
        ),
    ]
