# Generated by Django 6.0.7 on 2026-07-21 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_export', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer (عميل)',
                'verbose_name_plural': 'Customers (عملاء)',
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(help_text='الرقم التسلسلي لكود الجودة (1, 2, 3, 4, 5...)', unique=True)),
                ('produced_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Production Batch (كود الجودة)',
                'verbose_name_plural': 'Production Batches (أكواد الجودة)',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='SackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: شكارة 25 كيلو', max_length=30, unique=True)),
                ('nominal_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Sack Type (نوع الشكارة)',
                'verbose_name_plural': 'Sack Types (أنواع الشكاير)',
            },
        ),
        migrations.CreateModel(
            name='BigBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.PositiveIntegerField(help_text='الرقم التسلسلي للبيج باج', unique=True)),
                ('status', models.CharField(choices=[('SEALED', 'مقفول (في المخزن)'), ('SOLD_WHOLE', 'اتباع كامل'), ('CONVERTED_TO_SACKS', 'اتحول لشكاير')], default='SEALED', max_length=20)),
                ('packed_at', models.DateTimeField()),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='big_bags', to='production.productionbatch')),
            ],
            options={
                'verbose_name': 'Big Bag (بيج باج)',
                'verbose_name_plural': 'Big Bags (بيج باجات)',
                'ordering': ['bag_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(help_text='رقم التشغيلة (1، 2، 3...) لكل مصنع')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Production Run (تشغيلة)',
                'verbose_name_plural': 'Production Runs (تشغيلات)',
                'ordering': ['plant', 'run_number'],
                'unique_together': {('plant', 'run_number')},
            },
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='production_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='production.productionrun'),
        ),
        migrations.CreateModel(
            name='SackConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sack_count', models.PositiveIntegerField(help_text='عدد الشكاير الناتجة، مثلاً 40')),
                ('converted_at', models.DateTimeField()),
                ('big_bag', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sack_conversion', to='production.bigbag')),
                ('sack_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='production.sacktype')),
            ],
            options={
                'verbose_name': 'Sack Conversion (تحويل لشكاير)',
                'verbose_name_plural': 'Sack Conversions (تحويلات لشكاير)',
            },
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=50, unique=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_batches', to='production.customer')),
                ('whole_big_bags', models.ManyToManyField(blank=True, help_text='البيج باجات اللي اتباعت كاملة في الطلبية دي', related_name='order_batches', to='production.bigbag')),
                ('sack_conversions', models.ManyToManyField(blank=True, help_text='تحويلات الشكاير اللي اتباع منها في الطلبية دي', related_name='order_batches', to='production.sackconversion')),
            ],
            options={
                'verbose_name': 'Order Batch (باتش الطلبية)',
                'verbose_name_plural': 'Order Batches (أكواد الطلبيات)',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثال: A, B, C', max_length=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='silos', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Silo (سيلو)',
                'verbose_name_plural': 'Silos (سيلوهات)',
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='production.silo'),
        ),
    ]
