# Generated by Django 5.0.2 on 2026-08-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("plants", "0007_rename_plant_code_to_product_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_code", models.CharField(max_length=30, unique=True)),
                ("location_label", models.CharField(max_length=100)),
                (
                    "packing_type_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "packing_type_ref",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Reference to factory.PackingType PK",
                        null=True,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="plants.plant"
                    ),
                ),
            ],
            options={
                "db_table": "lab_sample_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_code", models.CharField(max_length=30, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("final_product", "Final Product"),
                            ("raw_material", "Raw Material"),
                            ("packaging_material", "Packaging Material"),
                            ("spare_part", "Spare Part"),
                            ("environmental", "Environmental"),
                            ("warehouse_stock", "Warehouse Stock"),
                            ("order_sample", "Order Sample"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("collected", "Collected"),
                            ("under_analysis", "Under Analysis"),
                            ("results_entered", "Results Entered"),
                            ("ready_for_decision", "Ready for Decision"),
                            ("decided", "Decided"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("ready_for_decision_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "lab_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plants.department",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="plants.plant"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="samples",
                        to="lab.samplegroup",
                    ),
                ),
            ],
            options={
                "db_table": "lab_samples",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SampleRequiredTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                (
                    "test_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_tests",
                        to="lab.sample",
                    ),
                ),
                (
                    "test_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_required_tests",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "lab_sample_required_tests",
                "unique_together": {("sample", "test_name")},
            },
        ),
        migrations.CreateModel(
            name="SampleTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                (
                    "test_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "result",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="lab.sample",
                    ),
                ),
                (
                    "test_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_test_results",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "lab_sample_test_results",
                "unique_together": {("sample", "test_name")},
            },
        ),
    ]
